from __future__ import annotations

from datetime import date, datetime

from sqlalchemy import (
    Boolean, Column, Date, DateTime, ForeignKey, Integer, Numeric, String, Table, Text, Time,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship

from app.core.time import utc_now
from app.db import Base
from app.models.types import EncryptedDecimal, EncryptedString

class FinancialStatementMapping(Base):
    __tablename__ = "financial_statement_mappings"
    __table_args__ = (UniqueConstraint("company_id", "account_id", name="uq_financial_mapping_company_account"),)
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    account_id = Column(Integer, ForeignKey("accounts.id", ondelete="CASCADE"), nullable=False, index=True)
    statement = Column(String(30), nullable=False, default="PROFIT_OR_LOSS")
    ifrs18_category = Column(String(30), nullable=False)
    line_code = Column(String(50), nullable=False, index=True)
    line_name_ar = Column(String(250), nullable=False)
    line_name_en = Column(String(250), nullable=False)
    sort_order = Column(Integer, nullable=False, default=100)
    is_oci = Column(Boolean, nullable=False, default=False)
    status = Column(String(20), nullable=False, default="DRAFT", index=True)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    approved_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, nullable=False, default=utc_now)
    approved_at = Column(DateTime)
    account = relationship("Account", lazy="joined")

class FinancialReportRun(Base):
    __tablename__ = "financial_report_runs"
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False, index=True)
    comparative_start_date = Column(Date)
    comparative_end_date = Column(Date)
    framework = Column(String(30), nullable=False, default="IFRS_18")
    status = Column(String(20), nullable=False, default="DRAFT", index=True)
    report_payload = Column(Text, nullable=False)
    validation_payload = Column(Text, nullable=False)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    approved_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, nullable=False, default=utc_now)
    approved_at = Column(DateTime)

class FinancialDisclosureNote(Base):
    __tablename__ = "financial_disclosure_notes"
    __table_args__ = (UniqueConstraint("company_id", "period_end", "note_code", name="uq_disclosure_company_period_code"),)
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    period_end = Column(Date, nullable=False, index=True)
    note_code = Column(String(40), nullable=False)
    title_ar = Column(String(250), nullable=False)
    title_en = Column(String(250), nullable=False)
    standard = Column(String(50), nullable=False)
    content_ar = Column(Text, nullable=False, default="")
    content_en = Column(Text, nullable=False, default="")
    supporting_reference = Column(String(500))
    status = Column(String(20), nullable=False, default="DRAFT", index=True)
    prepared_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    reviewed_by = Column(Integer, ForeignKey("users.id"))
    approved_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, nullable=False, default=utc_now)
    reviewed_at = Column(DateTime)
    approved_at = Column(DateTime)

class LeaseModification(Base):
    __tablename__ = "lease_modifications"
    id = Column(Integer, primary_key=True)
    lease_id = Column(Integer, ForeignKey("lease_contracts.id", ondelete="CASCADE"), nullable=False, index=True)
    effective_date = Column(Date, nullable=False, index=True)
    modification_type = Column(String(30), nullable=False, default="REMEASUREMENT")
    new_end_date = Column(Date, nullable=False)
    new_payment_amount = Column(Numeric(18, 2), nullable=False)
    new_discount_rate = Column(Numeric(9, 6), nullable=False)
    reason = Column(String(500), nullable=False)
    status = Column(String(20), nullable=False, default="DRAFT", index=True)
    carrying_liability = Column(Numeric(18, 2), nullable=False, default=0)
    remeasured_liability = Column(Numeric(18, 2), nullable=False, default=0)
    rou_adjustment = Column(Numeric(18, 2), nullable=False, default=0)
    journal_id = Column(Integer, ForeignKey("journal_entries.id"))
    created_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    approved_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, nullable=False, default=utc_now)
    approved_at = Column(DateTime)
    lease = relationship("LeaseContract", lazy="joined")
    journal = relationship("JournalEntry")

# -------------------- Corporate reporting, tax and impairment RC7 --------------------

class CorporateFinanceConfig(Base):
    __tablename__ = "corporate_finance_configs"
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    deferred_tax_asset_account_id = Column(Integer, ForeignKey("accounts.id"), nullable=False)
    deferred_tax_liability_account_id = Column(Integer, ForeignKey("accounts.id"), nullable=False)
    deferred_tax_expense_account_id = Column(Integer, ForeignKey("accounts.id"), nullable=False)
    deferred_tax_oci_account_id = Column(Integer, ForeignKey("accounts.id"), nullable=False)
    impairment_expense_account_id = Column(Integer, ForeignKey("accounts.id"), nullable=False)
    accumulated_impairment_account_id = Column(Integer, ForeignKey("accounts.id"), nullable=False)
    status = Column(String(20), nullable=False, default="DRAFT", index=True)
    configured_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    approved_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, nullable=False, default=utc_now)
    approved_at = Column(DateTime)

class DeferredTaxRun(Base):
    __tablename__ = "deferred_tax_runs"
    __table_args__ = (UniqueConstraint("company_id", "period_end", "version", name="uq_deferred_tax_run_period_version"),)
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    period_end = Column(Date, nullable=False, index=True)
    version = Column(Integer, nullable=False, default=1)
    default_tax_rate = Column(Numeric(9, 6), nullable=False)
    status = Column(String(30), nullable=False, default="DRAFT", index=True)
    total_recognized_dta = Column(Numeric(18, 2), nullable=False, default=0)
    total_recognized_dtl = Column(Numeric(18, 2), nullable=False, default=0)
    total_unrecognized_dta = Column(Numeric(18, 2), nullable=False, default=0)
    net_deferred_tax_position = Column(Numeric(18, 2), nullable=False, default=0)
    journal_id = Column(Integer, ForeignKey("journal_entries.id"))
    prepared_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    reviewed_by = Column(Integer, ForeignKey("users.id"))
    approved_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, nullable=False, default=utc_now)
    reviewed_at = Column(DateTime)
    approved_at = Column(DateTime)
    items = relationship("DeferredTaxItem", back_populates="run", cascade="all, delete-orphan", lazy="selectin")
    journal = relationship("JournalEntry")

class DeferredTaxItem(Base):
    __tablename__ = "deferred_tax_items"
    __table_args__ = (UniqueConstraint("run_id", "reference", name="uq_deferred_tax_item_reference"),)
    id = Column(Integer, primary_key=True)
    run_id = Column(Integer, ForeignKey("deferred_tax_runs.id", ondelete="CASCADE"), nullable=False, index=True)
    reference = Column(String(100), nullable=False)
    description_ar = Column(String(500), nullable=False)
    description_en = Column(String(500), nullable=False)
    source_account_id = Column(Integer, ForeignKey("accounts.id"))
    carrying_amount = Column(Numeric(18, 2), nullable=False)
    tax_base = Column(Numeric(18, 2), nullable=False)
    temporary_difference = Column(Numeric(18, 2), nullable=False)
    difference_type = Column(String(20), nullable=False)  # TAXABLE / DEDUCTIBLE
    tax_rate = Column(Numeric(9, 6), nullable=False)
    tax_effect = Column(Numeric(18, 2), nullable=False)
    recognition_status = Column(String(20), nullable=False, default="RECOGNIZED")
    presentation_basis = Column(String(20), nullable=False, default="PNL")  # PNL / OCI / EQUITY
    recoverability_evidence = Column(Text)
    run = relationship("DeferredTaxRun", back_populates="items")
    source_account = relationship("Account", lazy="joined")

class GoodwillImpairmentTest(Base):
    __tablename__ = "goodwill_impairment_tests"
    __table_args__ = (UniqueConstraint("company_id", "period_end", "cgu_code", name="uq_goodwill_test_company_period_cgu"),)
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    period_end = Column(Date, nullable=False, index=True)
    cgu_code = Column(String(50), nullable=False)
    cgu_name_ar = Column(String(250), nullable=False)
    cgu_name_en = Column(String(250), nullable=False)
    goodwill_carrying_amount = Column(Numeric(18, 2), nullable=False, default=0)
    other_assets_carrying_amount = Column(Numeric(18, 2), nullable=False, default=0)
    value_in_use = Column(Numeric(18, 2), nullable=False, default=0)
    fair_value_less_costs = Column(Numeric(18, 2), nullable=False, default=0)
    recoverable_amount = Column(Numeric(18, 2), nullable=False, default=0)
    impairment_loss = Column(Numeric(18, 2), nullable=False, default=0)
    goodwill_impairment = Column(Numeric(18, 2), nullable=False, default=0)
    other_asset_impairment = Column(Numeric(18, 2), nullable=False, default=0)
    assumptions_payload = Column(Text, nullable=False)
    sensitivity_payload = Column(Text, nullable=False)
    status = Column(String(30), nullable=False, default="DRAFT", index=True)
    journal_id = Column(Integer, ForeignKey("journal_entries.id"))
    prepared_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    reviewed_by = Column(Integer, ForeignKey("users.id"))
    approved_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, nullable=False, default=utc_now)
    reviewed_at = Column(DateTime)
    approved_at = Column(DateTime)
    journal = relationship("JournalEntry")

class ForeignOperationTranslationRun(Base):
    __tablename__ = "foreign_operation_translation_runs"
    __table_args__ = (UniqueConstraint("group_id", "member_company_id", "period_end", name="uq_translation_group_member_period"),)
    id = Column(Integer, primary_key=True)
    group_id = Column(Integer, ForeignKey("consolidation_groups.id", ondelete="CASCADE"), nullable=False, index=True)
    member_company_id = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    period_start = Column(Date, nullable=False)
    period_end = Column(Date, nullable=False, index=True)
    functional_currency = Column(String(3), nullable=False)
    reporting_currency = Column(String(3), nullable=False)
    closing_rate = Column(Numeric(18, 8), nullable=False)
    average_rate = Column(Numeric(18, 8), nullable=False)
    historical_equity_rate = Column(Numeric(18, 8), nullable=False)
    foreign_assets = Column(Numeric(18, 2), nullable=False, default=0)
    foreign_liabilities = Column(Numeric(18, 2), nullable=False, default=0)
    foreign_equity = Column(Numeric(18, 2), nullable=False, default=0)
    foreign_revenue = Column(Numeric(18, 2), nullable=False, default=0)
    foreign_expenses = Column(Numeric(18, 2), nullable=False, default=0)
    translated_net_assets = Column(Numeric(18, 2), nullable=False, default=0)
    translated_equity = Column(Numeric(18, 2), nullable=False, default=0)
    translated_profit = Column(Numeric(18, 2), nullable=False, default=0)
    cta_amount = Column(Numeric(18, 2), nullable=False, default=0)
    status = Column(String(30), nullable=False, default="DRAFT", index=True)
    prepared_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    reviewed_by = Column(Integer, ForeignKey("users.id"))
    approved_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, nullable=False, default=utc_now)
    reviewed_at = Column(DateTime)
    approved_at = Column(DateTime)

class ManagementPerformanceMeasure(Base):
    __tablename__ = "management_performance_measures"
    __table_args__ = (UniqueConstraint("company_id", "period_end", "code", name="uq_mpm_company_period_code"),)
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    period_end = Column(Date, nullable=False, index=True)
    code = Column(String(50), nullable=False)
    name_ar = Column(String(250), nullable=False)
    name_en = Column(String(250), nullable=False)
    explanation_ar = Column(Text, nullable=False)
    explanation_en = Column(Text, nullable=False)
    base_report_run_id = Column(Integer, ForeignKey("financial_report_runs.id"), nullable=False)
    base_subtotal_code = Column(String(80), nullable=False)
    base_amount = Column(Numeric(18, 2), nullable=False)
    adjustments_payload = Column(Text, nullable=False)
    total_adjustments = Column(Numeric(18, 2), nullable=False, default=0)
    tax_effect = Column(Numeric(18, 2), nullable=False, default=0)
    nci_effect = Column(Numeric(18, 2), nullable=False, default=0)
    measure_value = Column(Numeric(18, 2), nullable=False)
    status = Column(String(30), nullable=False, default="DRAFT", index=True)
    prepared_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    reviewed_by = Column(Integer, ForeignKey("users.id"))
    approved_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, nullable=False, default=utc_now)
    reviewed_at = Column(DateTime)
    approved_at = Column(DateTime)

class EarningsPerShareRun(Base):
    __tablename__ = "earnings_per_share_runs"
    __table_args__ = (UniqueConstraint("company_id", "period_end", "version", name="uq_eps_company_period_version"),)
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    period_end = Column(Date, nullable=False, index=True)
    version = Column(Integer, nullable=False, default=1)
    profit_attributable = Column(Numeric(18, 2), nullable=False)
    preference_dividends = Column(Numeric(18, 2), nullable=False, default=0)
    weighted_average_shares = Column(Numeric(18, 4), nullable=False)
    diluted_profit_adjustment = Column(Numeric(18, 2), nullable=False, default=0)
    incremental_shares = Column(Numeric(18, 4), nullable=False, default=0)
    basic_eps = Column(Numeric(18, 6), nullable=False)
    diluted_eps = Column(Numeric(18, 6), nullable=False)
    anti_dilutive_excluded = Column(Numeric(18, 4), nullable=False, default=0)
    support_reference = Column(String(500), nullable=False)
    status = Column(String(30), nullable=False, default="DRAFT", index=True)
    prepared_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    reviewed_by = Column(Integer, ForeignKey("users.id"))
    approved_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, nullable=False, default=utc_now)
    reviewed_at = Column(DateTime)
    approved_at = Column(DateTime)

class OperatingSegment(Base):
    __tablename__ = "operating_segments"
    __table_args__ = (UniqueConstraint("company_id", "code", name="uq_operating_segment_company_code"),)
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    code = Column(String(50), nullable=False)
    name_ar = Column(String(250), nullable=False)
    name_en = Column(String(250), nullable=False)
    codm_title = Column(String(250), nullable=False)
    reportable = Column(Boolean, nullable=False, default=True)
    active = Column(Boolean, nullable=False, default=True)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    approved_by = Column(Integer, ForeignKey("users.id"))
    status = Column(String(20), nullable=False, default="DRAFT", index=True)
    created_at = Column(DateTime, nullable=False, default=utc_now)
    approved_at = Column(DateTime)

class SegmentReportRun(Base):
    __tablename__ = "segment_report_runs"
    __table_args__ = (UniqueConstraint("company_id", "period_end", "version", name="uq_segment_report_company_period_version"),)
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    period_end = Column(Date, nullable=False, index=True)
    version = Column(Integer, nullable=False, default=1)
    base_report_run_id = Column(Integer, ForeignKey("financial_report_runs.id"), nullable=False)
    status = Column(String(30), nullable=False, default="DRAFT", index=True)
    reconciliation_payload = Column(Text, nullable=False)
    prepared_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    reviewed_by = Column(Integer, ForeignKey("users.id"))
    approved_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(DateTime, nullable=False, default=utc_now)
    reviewed_at = Column(DateTime)
    approved_at = Column(DateTime)
    lines = relationship("SegmentReportLine", back_populates="run", cascade="all, delete-orphan", lazy="selectin")

class SegmentReportLine(Base):
    __tablename__ = "segment_report_lines"
    __table_args__ = (UniqueConstraint("run_id", "segment_id", name="uq_segment_report_line_segment"),)
    id = Column(Integer, primary_key=True)
    run_id = Column(Integer, ForeignKey("segment_report_runs.id", ondelete="CASCADE"), nullable=False, index=True)
    segment_id = Column(Integer, ForeignKey("operating_segments.id", ondelete="CASCADE"), nullable=False, index=True)
    external_revenue = Column(Numeric(18, 2), nullable=False, default=0)
    intersegment_revenue = Column(Numeric(18, 2), nullable=False, default=0)
    segment_profit = Column(Numeric(18, 2), nullable=False, default=0)
    segment_assets = Column(Numeric(18, 2), nullable=False, default=0)
    segment_liabilities = Column(Numeric(18, 2), nullable=False, default=0)
    measurement_basis = Column(String(500), nullable=False)
    run = relationship("SegmentReportRun", back_populates="lines")
    segment = relationship("OperatingSegment", lazy="joined")

# -------------------- Financial close workbench RC8 --------------------

__all__ = ['FinancialStatementMapping', 'FinancialReportRun', 'FinancialDisclosureNote', 'LeaseModification', 'CorporateFinanceConfig', 'DeferredTaxRun', 'DeferredTaxItem', 'GoodwillImpairmentTest', 'ForeignOperationTranslationRun', 'ManagementPerformanceMeasure', 'EarningsPerShareRun', 'OperatingSegment', 'SegmentReportRun', 'SegmentReportLine']
