import { useState } from 'react';
import { LockKeyhole, Mail, Languages, ArrowLeft, ArrowRight, ShieldCheck } from 'lucide-react';
import '../styles/auth.css';

type Lang='ar'|'en';
export function Login({lang,setLang,onLogin}:{lang:Lang,setLang:(l:Lang)=>void,onLogin:()=>void}){
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [otp,setOtp]=useState(''); const [needsOtp,setNeedsOtp]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const ar=lang==='ar'; const Arrow=ar?ArrowLeft:ArrowRight;
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');try{const res=await fetch('/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,otp:otp||null})});const payload=await res.json().catch(()=>({}));if(!res.ok){const detail=String(payload.detail||'');if(detail.toLowerCase().includes('mfa')){setNeedsOtp(true);throw new Error(ar?'أدخل رمز المصادقة الثنائية من تطبيق المصادقة.':'Enter the MFA code from your authenticator app.')}throw new Error(detail|| (ar?'تعذر تسجيل الدخول.':'Login failed.'));}sessionStorage.setItem('corvax_token',payload.access_token);localStorage.setItem('corvax_user',JSON.stringify(payload.user));onLogin();}catch(err:any){setError(err.message|| (ar?'تعذر تسجيل الدخول.':'Login failed.'));}finally{setLoading(false)}}
 return <main className="auth-page" dir={ar?'rtl':'ltr'}><button className="auth-lang" onClick={()=>setLang(ar?'en':'ar')}><Languages size={17}/>{ar?'English':'العربية'}</button><aside className="auth-showcase"><div className="auth-brand"><div className="corvax-symbol"><span>C</span></div><div><strong>CORVAX</strong><small>THE CORE BUSINESS PLATFORM</small></div></div><div className="showcase-copy"><span>{ar?'منصة أعمال مؤسسية متكاملة':'Unified enterprise business platform'}</span><h2>{ar?'رؤية واحدة لكل أعمالك.':'One view for your entire business.'}</h2><p>{ar?'المالية والتصنيع وسلسلة الإمداد والموارد البشرية والحوكمة—في منصة واحدة مترابطة.':'Finance, manufacturing, supply chain, people and governance—connected in one platform.'}</p></div><div className="showcase-metrics"><article><strong>121+</strong><span>{ar?'جدول مترابط':'connected tables'}</span></article><article><strong>26</strong><span>{ar?'محرك أعمال':'business engines'}</span></article><article><strong>AR / EN</strong><span>{ar?'ثنائي اللغة':'bilingual'}</span></article></div><div className="showcase-security"><ShieldCheck size={18}/><span>{ar?'صلاحيات مؤسسية · MFA · سجل تدقيق':'Enterprise access · MFA · Audit trail'}</span></div></aside><section className="auth-card"><div className="brand large mobile-auth-brand"><div className="corvax-symbol"><span>C</span></div><div><strong>CORVAX</strong><span>THE CORE BUSINESS PLATFORM</span></div></div><div className="auth-copy"><span>{ar?'الوصول الآمن':'SECURE ACCESS'}</span><h1>{ar?'مرحبًا بعودتك':'Welcome back'}</h1><p>{ar?'سجّل الدخول للوصول إلى شركاتك ولوحات العمل.':'Sign in to access your companies and workspaces.'}</p></div><form onSubmit={submit}><label>{ar?'اسم المستخدم أو البريد':'Username or email'}<div className="field"><Mail size={18}/><input value={email} onChange={e=>setEmail(e.target.value)} type="text" required/></div></label><label>{ar?'كلمة المرور':'Password'}<div className="field"><LockKeyhole size={18}/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></div></label>{needsOtp&&<label>{ar?'رمز المصادقة الثنائية':'MFA code'}<div className="field"><ShieldCheck size={18}/><input value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" pattern="[0-9]{6}" placeholder="000000" required/></div></label>}{error&&<div className="error">{error}</div>}<button className="primary-btn" disabled={loading}>{loading?(ar?'جارٍ الدخول...':'Signing in...'):(ar?'تسجيل الدخول':'Sign in')}<Arrow size={18}/></button></form><div className="demo-note">{ar?'دخول آمن مع دعم المصادقة الثنائية':'Secure sign-in with MFA support'}</div></section></main>
}
