import {
  BadgeDollarSign, BookOpenCheck, Boxes, Building2, CalendarRange, ClipboardCheck,
  DatabaseBackup, Dumbbell, Factory, FileCheck2, KeyRound, Landmark, LayoutDashboard,
  MonitorCog, Network, ShieldCheck, Workflow, ShoppingCart, TrendingUp, Users, UtensilsCrossed, WalletCards, RotateCcw, Percent, Flame, Calculator, Wrench, Truck, Scale, FileBarChart, HardHat, NotebookPen, UserCog } from 'lucide-react';
import type { NavGroupKey, NavItem } from './types';

// Sidebar groups, in display order. Sections without a group render above these,
// so the two entry points (work centre, executive) stay one click away.
export const NAV_GROUPS: {key: NavGroupKey; ar: string; en: string}[] = [
  {key: 'finance',     ar: 'المالية والمحاسبة',      en: 'Finance & Accounting'},
  {key: 'tax',         ar: 'الضرائب والزكاة',        en: 'Tax & Zakat'},
  {key: 'assets',      ar: 'الأصول والالتزامات',     en: 'Assets & Obligations'},
  {key: 'procurement', ar: 'المشتريات والمخزون',     en: 'Procurement & Inventory'},
  {key: 'sales',       ar: 'المبيعات والعملاء',      en: 'Sales & Customers'},
  {key: 'production',  ar: 'التصنيع والجودة',        en: 'Manufacturing & Quality'},
  {key: 'operations',  ar: 'العمليات',               en: 'Operations'},
  {key: 'people',      ar: 'الموارد البشرية',        en: 'People'},
  {key: 'governance',  ar: 'الحوكمة والامتثال',      en: 'Governance & Compliance'},
  {key: 'system',      ar: 'النظام والإعدادات',      en: 'System & Settings'},
];


const allScopes: NavItem['scope'] = ['holding', 'gym', 'restaurant', 'manufacturing'];
export const navItems: NavItem[] = [
  { key: 'workbench', ar: 'مركز العمل والبحث', en: 'Work Center & Search', icon: Workflow, scope: allScopes },
  { key: 'finalCompletion', ar: 'الإكمال الداخلي والجاهزية', en: 'Internal Completion & Readiness', icon: FileCheck2, scope: allScopes, group: 'system' },
  { key: 'executive', ar: 'مركز القرار', en: 'Executive Center', icon: LayoutDashboard, scope: allScopes },
  { key: 'core', ar: 'الشركات والإعدادات', en: 'Enterprise Core', icon: Building2, scope: allScopes , group: 'system' },
  { key: 'finance', ar: 'القوائم المالية', en: 'Financial Statements', icon: Landmark, scope: allScopes, group: 'finance', requires: ['finance'] },
  { key: 'cipProjects', ar: 'مشروعات تحت التنفيذ', en: 'Projects Under Construction', icon: HardHat, scope: allScopes, group: 'assets', requires: ['cip'] },
  { key: 'reports', ar: 'مركز التقارير', en: 'Reports Center', icon: FileBarChart, scope: allScopes, group: 'finance', requires: ['finance'] },
  { key: 'aging', ar: 'أعمار العملاء والموردين', en: 'AR/AP Aging & Allocation', icon: WalletCards, scope: allScopes, group: 'finance' },
  { key: 'returns', ar: 'المرتجعات والإشعارات الدائنة', en: 'Returns & Credit Notes', icon: RotateCcw, scope: allScopes , group: 'tax' },
  { key: 'withholdingTax', ar: 'ضريبة الاستقطاع', en: 'Withholding Tax', icon: Percent, scope: allScopes, group: 'tax' },
  { key: 'exciseTax', ar: 'الضريبة الانتقائية', en: 'Excise Tax', icon: Flame, scope: allScopes, group: 'tax' },
  { key: 'zakatIncomeTax', ar: 'الزكاة وضريبة الدخل', en: 'Zakat & Income Tax', icon: Calculator, scope: allScopes, group: 'tax' },
  { key: 'budget', ar: 'الموازنة والرقابة', en: 'Budget Control', icon: WalletCards, scope: allScopes , group: 'finance' },
  { key: 'transactions', ar: 'الحسابات والقيود', en: 'Accounting Operations', icon: BookOpenCheck, scope: allScopes, group: 'finance', requires: ['finance'] },
  { key: 'manualJournals', ar: 'قيود اليومية', en: 'Journal Entries', icon: NotebookPen, scope: allScopes, group: 'finance', requires: ['finance'] },
  { key: 'treasury', ar: 'الخزينة والتسويات', en: 'Treasury & Reconciliation', icon: Landmark, scope: allScopes, group: 'finance', requires: ['banking'] },
  { key: 'leases', ar: 'عقود الإيجار IFRS 16', en: 'IFRS 16 Leases', icon: CalendarRange, scope: allScopes, group: 'assets', requires: ['leases'] },
  { key: 'assets', ar: 'الأصول الثابتة IAS 16', en: 'IAS 16 Fixed Assets', icon: BadgeDollarSign, scope: allScopes, group: 'assets', requires: ['assets'] },
  { key: 'prepaids', ar: 'المصروفات المدفوعة مقدمًا', en: 'Prepaid Expenses', icon: CalendarRange, scope: allScopes, group: 'assets', requires: ['prepaids'] },
  { key: 'accruals', ar: 'الاستحقاقات والقيود المتكررة', en: 'Accruals & Recurring Journals', icon: CalendarRange, scope: allScopes, group: 'assets', requires: ['accruals'] },
  { key: 'inventory', ar: 'المخزون والمستودعات', en: 'Inventory', icon: Boxes, scope: allScopes, group: 'procurement', requires: ['inventory'] },
  { key: 'inventoryTraceability', ar: 'تتبع المخزون والشحنات', en: 'Inventory Traceability', icon: Boxes, scope: allScopes, group: 'procurement' },
  { key: 'operationalControls', ar: 'الاستيراد والجمارك والتكلفة', en: 'Import, Customs & Costing', icon: FileCheck2, scope: allScopes, group: 'procurement' },
  { key: 'sales', ar: 'المبيعات', en: 'Sales', icon: ShoppingCart, scope: allScopes, requires: ['subledgers'] , group: 'sales' },
  { key: 'purchases', ar: 'المشتريات', en: 'Purchases', icon: ShoppingCart, scope: allScopes, group: 'procurement', requires: ['subledgers'] },
  { key: 'maintenance', ar: 'الصيانة', en: 'Maintenance', icon: Wrench, scope: allScopes, group: 'operations', requires: ['maintenance'] },
  { key: 'fleet', ar: 'اللوجستيك وحركة السيارات', en: 'Logistics & Fleet', icon: Truck, scope: allScopes, group: 'operations', requires: ['fleet'] },
  { key: 'legal', ar: 'الشؤون القانونية', en: 'Legal Affairs', icon: Scale, scope: allScopes, requires: ['legal'] , group: 'governance' },
  { key: 'crm', ar: 'العملاء والتسويق', en: 'CRM & Marketing', icon: TrendingUp, scope: allScopes, group: 'sales' },
  { key: 'gym', ar: 'إدارة النادي', en: 'Gym Management', icon: Dumbbell, scope: ['holding', 'gym'] , group: 'operations' },
  { key: 'restaurant', ar: 'المطاعم ونقاط البيع', en: 'Restaurant & POS', icon: UtensilsCrossed, scope: ['holding', 'restaurant'], group: 'sales' },
  { key: 'manufacturing', ar: 'التصنيع والتكاليف', en: 'Manufacturing & Costing', icon: Factory, scope: ['holding', 'manufacturing'], group: 'production' },
  { key: 'quality', ar: 'الجودة والفحص', en: 'Quality & Inspection', icon: ClipboardCheck, scope: ['holding', 'restaurant', 'manufacturing'], group: 'production' },
  { key: 'foodSafety', ar: 'سلامة الغذاء وHACCP', en: 'Food Safety & HACCP', icon: ShieldCheck, scope: ['holding', 'restaurant', 'manufacturing'], group: 'production' },
  { key: 'hr', ar: 'الموارد والرواتب', en: 'HR & Payroll', icon: Users, scope: allScopes, requires: ['payroll'] , group: 'people' },
  { key: 'close', ar: 'الإقفال المالي', en: 'Financial Close', icon: FileCheck2, scope: allScopes, group: 'finance', requires: ['period'] },
  { key: 'assurance', ar: 'التأكيد المالي الحازم', en: 'Financial Assurance Gate', icon: ShieldCheck, scope: allScopes, group: 'finance' },
  { key: 'compliance', ar: 'الالتزام والضرائب', en: 'Compliance & Tax', icon: ShieldCheck, scope: allScopes, group: 'tax', requires: ['compliance'] },
  { key: 'security', ar: 'الأمان والنسخ الاحتياطي', en: 'Security & Backup', icon: DatabaseBackup, scope: allScopes, requires: ['security'] , group: 'system' },
  { key: 'users', ar: 'المستخدمون', en: 'Users', icon: UserCog, scope: allScopes, group: 'system', requires: ['users'] },
  { key: 'accessGovernance', ar: 'حوكمة الصلاحيات', en: 'Access Governance', icon: KeyRound, scope: allScopes, requires: ['access'] , group: 'governance' },
  { key: 'fx', ar: 'العملات والتوحيد', en: 'FX & Consolidation', icon: Network, scope: allScopes, group: 'finance', requires: ['fx'] },
  { key: 'audit', ar: 'المراجعة والحوكمة', en: 'Audit & Governance', icon: ShieldCheck, scope: allScopes, group: 'governance', requires: ['audit'] },
  { key: 'it', ar: 'الإدارة الإلكترونية', en: 'Digital & IT', icon: MonitorCog, scope: allScopes, group: 'system' },
];
