import {useEffect, useMemo, useState} from 'react';
import {Calculator, Download, FileCheck2, Landmark, Scale, ShieldCheck} from 'lucide-react';
import {apiFetch} from '../api/client';
import {DataTable, Kpi, Panel, money} from './ui';

type Profile={company_id:number;return_basis:string;saudi_gcc_ownership_percent:number;non_saudi_ownership_percent:number;zakat_rate_hijri:number;hijri_year_days:number;income_tax_rate:number;tax_loss_utilization_cap_percent:number;zakat_registration_number?:string;cit_registration_number?:string;minimum_zakat_amount:number;notes?:string};
type Loss={id:number;origin_year:number;original_amount:number;utilized_amount:number;available_amount:number;status:string;evidence_reference?:string};
type Adjustment={id:number;regime:string;direction:string;code:string;description_ar:string;description_en:string;amount:number;source_account_code?:string;evidence_reference?:string};
type TaxReturn={id:number;number:string;period_start:string;period_end:string;due_date:string;status:string;calculation_status:string;accounting_profit_before_zakat_tax:number;cit_additions:number;cit_deductions:number;income_tax_base:number;income_tax_rate:number;gross_income_tax:number;cit_credits:number;income_tax_payable:number;gross_zakat_base:number;zakat_base:number;zakat_rate:number;gross_zakat:number;zakat_credits:number;zakat_payable:number;total_payable:number;gl_payable:number;reconciliation_difference:number;adjustments:Adjustment[];loss_usages:{loss_id:number;origin_year:number;amount:number}[]};
type Bank={id:number;code:string;bank_name_ar:string;bank_name_en:string};

async function json(url:string,init?:RequestInit){const r=await apiFetch(url,init);const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof x.detail==='string'?x.detail:JSON.stringify(x.detail||x));return x;}
async function download(url:string,name:string){const r=await apiFetch(url);if(!r.ok)throw new Error('Export failed');const b=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();URL.revokeObjectURL(a.href);}
const inputStyle={display:'block',width:'100%',marginTop:5,padding:9,border:'1px solid var(--border)',borderRadius:9};

export function ZakatIncomeTaxPage({ar,companyId}:{ar:boolean;companyId:number}){
  const year=new Date().getFullYear()-1; const today=new Date().toISOString().slice(0,10);
  const [profile,setProfile]=useState<Profile|null>(null); const [losses,setLosses]=useState<Loss[]>([]); const [returns,setReturns]=useState<TaxReturn[]>([]); const [banks,setBanks]=useState<Bank[]>([]);
  const [basis,setBasis]=useState('MIXED'); const [saudi,setSaudi]=useState('100'); const [foreign,setForeign]=useState('0'); const [zakatRate,setZakatRate]=useState('2.5'); const [citRate,setCitRate]=useState('20'); const [lossCap,setLossCap]=useState('25'); const [zakatReg,setZakatReg]=useState(''); const [citReg,setCitReg]=useState('');
  const [returnYear,setReturnYear]=useState(String(year)); const [zakatCredits,setZakatCredits]=useState('0'); const [citCredits,setCitCredits]=useState('0');
  const [selectedReturnId,setSelectedReturnId]=useState(''); const [regime,setRegime]=useState('CIT'); const [direction,setDirection]=useState('ADD'); const [code,setCode]=useState('NON_DEDUCTIBLE_EXPENSE'); const [descriptionAr,setDescriptionAr]=useState('مصروف غير جائز الحسم'); const [descriptionEn,setDescriptionEn]=useState('Non-deductible expense'); const [adjustmentAmount,setAdjustmentAmount]=useState('0'); const [sourceAccount,setSourceAccount]=useState(''); const [evidence,setEvidence]=useState('');
  const [lossYear,setLossYear]=useState(String(year-1)); const [lossAmount,setLossAmount]=useState('0'); const [lossEvidence,setLossEvidence]=useState('');
  const [bankId,setBankId]=useState(''); const [sadad,setSadad]=useState(''); const [paymentReference,setPaymentReference]=useState(''); const [paymentDate,setPaymentDate]=useState(today);
  const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);

  const load=async()=>{try{const [ls,rs,bs]=await Promise.all([json(`/api/v1/zakat-income-tax/losses?company_id=${companyId}`),json(`/api/v1/zakat-income-tax/returns?company_id=${companyId}`),json(`/api/v1/subledgers/bank-accounts?company_id=${companyId}`)]);setLosses(ls||[]);setReturns(rs||[]);setBanks(bs||[]);if(!selectedReturnId&&rs?.length)setSelectedReturnId(String(rs[0].id));if(!bankId&&bs?.length)setBankId(String(bs[0].id));try{const p=await json(`/api/v1/zakat-income-tax/profiles/${companyId}`);setProfile(p);setBasis(p.return_basis);setSaudi(String(p.saudi_gcc_ownership_percent));setForeign(String(p.non_saudi_ownership_percent));setZakatRate(String(p.zakat_rate_hijri));setCitRate(String(p.income_tax_rate));setLossCap(String(p.tax_loss_utilization_cap_percent));setZakatReg(p.zakat_registration_number||'');setCitReg(p.cit_registration_number||'');}catch{setProfile(null)}}catch(e:any){setMessage(String(e.message||e));}};
  useEffect(()=>{load()},[companyId]);
  const selected=useMemo(()=>returns.find(x=>String(x.id)===selectedReturnId),[returns,selectedReturnId]);
  const approvedUnpaid=returns.find(x=>x.status==='APPROVED'&&Number(x.total_payable)>0);

  async function saveProfile(){setBusy(true);setMessage('');try{await json('/api/v1/zakat-income-tax/profiles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({company_id:companyId,zakat_registration_number:zakatReg||null,cit_registration_number:citReg||null,return_basis:basis,saudi_gcc_ownership_percent:Number(saudi),non_saudi_ownership_percent:Number(foreign),zakat_rate_hijri:Number(zakatRate),hijri_year_days:354,income_tax_rate:Number(citRate),tax_loss_utilization_cap_percent:Number(lossCap),zakat_method:'FINANCING_SOURCES_LESS_DEDUCTIBLE_ASSETS',minimum_zakat_amount:0,notes:'RC24 preparation profile; final filing requires tax review'})});setMessage(ar?'تم حفظ ملف المكلف.':'Taxpayer profile saved.');await load();}catch(e:any){setMessage(String(e.message||e));}finally{setBusy(false)}}
  async function createLoss(){setBusy(true);setMessage('');try{await json('/api/v1/zakat-income-tax/losses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({company_id:companyId,origin_year:Number(lossYear),original_amount:Number(lossAmount),evidence_reference:lossEvidence||null,notes:null})});setMessage(ar?'تم تسجيل الخسارة المرحلة.':'Tax loss carryforward recorded.');await load();}catch(e:any){setMessage(String(e.message||e));}finally{setBusy(false)}}
  async function createReturn(){const y=Number(returnYear);setBusy(true);setMessage('');try{const r=await json('/api/v1/zakat-income-tax/returns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({company_id:companyId,period_start:`${y}-01-01`,period_end:`${y}-12-31`,zakat_credits:Number(zakatCredits),cit_credits:Number(citCredits),notes:'Internal annual return preparation'})});setSelectedReturnId(String(r.id));setMessage(ar?'تم إنشاء الإقرار السنوي.':'Annual return created.');await load();}catch(e:any){setMessage(String(e.message||e));}finally{setBusy(false)}}
  async function addAdjustment(){if(!selectedReturnId)return;setBusy(true);setMessage('');try{await json(`/api/v1/zakat-income-tax/returns/${selectedReturnId}/adjustments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({regime,direction,code,description_ar:descriptionAr,description_en:descriptionEn,amount:Number(adjustmentAmount),source_account_code:sourceAccount||null,evidence_reference:evidence||null,recurring:false})});setMessage(ar?'تمت إضافة التعديل وإعادة الاحتساب.':'Adjustment added and return recalculated.');await load();}catch(e:any){setMessage(String(e.message||e));}finally{setBusy(false)}}
  async function action(id:number,endpoint:string){setBusy(true);setMessage('');try{await json(`/api/v1/zakat-income-tax/returns/${id}/${endpoint}`,{method:'POST'});setMessage(ar?'تم تنفيذ الإجراء.':'Action completed.');await load();}catch(e:any){setMessage(String(e.message||e));}finally{setBusy(false)}}
  async function pay(){if(!approvedUnpaid)return;setBusy(true);setMessage('');try{await json(`/api/v1/zakat-income-tax/returns/${approvedUnpaid.id}/pay`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bank_account_id:Number(bankId),payment_date:paymentDate,sadad_invoice_number:sadad,payment_reference:paymentReference})});setMessage(ar?'تم سداد الإقرار وترحيل القيد.':'Return paid and journal posted.');await load();}catch(e:any){setMessage(String(e.message||e));}finally{setBusy(false)}}

  return <>
    <div className="page-heading"><div><h1>{ar?'الزكاة وضريبة الدخل':'Zakat & Corporate Income Tax'}</h1><p>{ar?'إعداد الوعاء، التعديلات، الخسائر المرحلة، الإقرار السنوي والمطابقة مع الأستاذ.':'Taxpayer profile, adjustments, losses, annual return and GL reconciliation.'}</p></div><ShieldCheck size={34}/></div>
    <div className="kpis rich"><Kpi icon={<Scale/>} title={ar?'أساس المكلف':'Return basis'} value={profile?.return_basis||'—'} trend={ar?'حسب هيكل الملكية':'Ownership-based'} good/><Kpi icon={<Calculator/>} title={ar?'إجمالي المستحق':'Total payable'} value={money.format(Number(returns[0]?.total_payable||0))} trend={returns[0]?.status||'—'} good={Number(returns[0]?.reconciliation_difference||0)===0}/><Kpi icon={<Landmark/>} title={ar?'الخسائر المتاحة':'Available losses'} value={money.format(losses.reduce((s,x)=>s+Number(x.available_amount||0),0))} trend={ar?'خاضعة لحد الاستخدام':'Subject to utilization cap'} good/><Kpi icon={<FileCheck2/>} title={ar?'فرق المطابقة':'GL difference'} value={money.format(Number(returns[0]?.reconciliation_difference||0))} trend={ar?'الإقرار مقابل الأستاذ':'Return vs GL'} good={Number(returns[0]?.reconciliation_difference||0)===0}/></div>

    <Panel title={ar?'ملف المكلف ونسب الملكية':'Taxpayer profile and ownership'} icon={<ShieldCheck size={18}/> }>
      <div className="journal-form" style={{gridTemplateColumns:'repeat(4,minmax(0,1fr))'}}>
        <label>{ar?'أساس الإقرار':'Return basis'}<select value={basis} onChange={e=>setBasis(e.target.value)} style={inputStyle}><option value="ZAKAT">ZAKAT</option><option value="CIT">CIT</option><option value="MIXED">MIXED</option></select></label>
        <label>{ar?'ملكية سعودية/خليجية %':'Saudi/GCC ownership %'}<input type="number" value={saudi} onChange={e=>setSaudi(e.target.value)}/></label>
        <label>{ar?'ملكية غير سعودية %':'Non-Saudi ownership %'}<input type="number" value={foreign} onChange={e=>setForeign(e.target.value)}/></label>
        <label>{ar?'معدل الزكاة الهجري %':'Hijri zakat rate %'}<input type="number" step="0.000001" value={zakatRate} onChange={e=>setZakatRate(e.target.value)}/></label>
        <label>{ar?'معدل ضريبة الدخل %':'CIT rate %'}<input type="number" step="0.000001" value={citRate} onChange={e=>setCitRate(e.target.value)}/></label>
        <label>{ar?'حد استخدام الخسائر %':'Loss utilization cap %'}<input type="number" value={lossCap} onChange={e=>setLossCap(e.target.value)}/></label>
        <label>{ar?'رقم تسجيل الزكاة':'Zakat registration'}<input value={zakatReg} onChange={e=>setZakatReg(e.target.value)}/></label>
        <label>{ar?'رقم تسجيل ضريبة الدخل':'CIT registration'}<input value={citReg} onChange={e=>setCitReg(e.target.value)}/></label>
      </div><div className="journal-footer"><span>{ar?'يجب أن يكون مجموع نسب الملكية 100%.':'Ownership percentages must total 100%.'}</span><button disabled={busy} onClick={saveProfile}>{ar?'حفظ الملف':'Save profile'}</button></div>
    </Panel>

    <div className="two-columns wide-left">
      <Panel title={ar?'إنشاء الإقرار السنوي':'Create annual return'} icon={<Calculator size={18}/> }>
        <div className="journal-form" style={{gridTemplateColumns:'repeat(3,minmax(0,1fr))'}}><label>{ar?'السنة':'Year'}<input type="number" value={returnYear} onChange={e=>setReturnYear(e.target.value)}/></label><label>{ar?'دفعات زكاة مقدمة':'Zakat credits'}<input type="number" value={zakatCredits} onChange={e=>setZakatCredits(e.target.value)}/></label><label>{ar?'دفعات ضريبة دخل مقدمة':'CIT credits'}<input type="number" value={citCredits} onChange={e=>setCitCredits(e.target.value)}/></label></div><div className="journal-footer"><span>{ar?'موعد الاستحقاق يحسب بعد 120 يومًا من نهاية السنة.':'Due date is calculated 120 days after year end.'}</span><button disabled={busy||!profile} onClick={createReturn}>{ar?'إنشاء واحتساب':'Create & calculate'}</button></div>
      </Panel>
      <Panel title={ar?'الخسائر الضريبية المرحلة':'Tax loss carryforwards'} icon={<Landmark size={18}/> }>
        <div className="journal-form" style={{gridTemplateColumns:'repeat(3,minmax(0,1fr))'}}><label>{ar?'سنة الخسارة':'Loss year'}<input type="number" value={lossYear} onChange={e=>setLossYear(e.target.value)}/></label><label>{ar?'المبلغ':'Amount'}<input type="number" value={lossAmount} onChange={e=>setLossAmount(e.target.value)}/></label><label>{ar?'مرجع الإثبات':'Evidence reference'}<input value={lossEvidence} onChange={e=>setLossEvidence(e.target.value)}/></label></div><div className="journal-footer"><span>{ar?'الاستخدام يتم آليًا حسب الأقدم وفي حدود الملف الضريبي.':'Oldest losses are applied automatically within profile controls.'}</span><button disabled={busy} onClick={createLoss}>{ar?'إضافة الخسارة':'Add loss'}</button></div>
      </Panel>
    </div>

    <Panel title={ar?'التعديلات الزكوية والضريبية':'Zakat and CIT adjustments'} icon={<Scale size={18}/> }>
      <div className="journal-form" style={{gridTemplateColumns:'repeat(4,minmax(0,1fr))'}}>
        <label>{ar?'الإقرار':'Return'}<select value={selectedReturnId} onChange={e=>setSelectedReturnId(e.target.value)} style={inputStyle}><option value="">—</option>{returns.map(x=><option key={x.id} value={x.id}>{x.number} — {x.status}</option>)}</select></label>
        <label>{ar?'النظام':'Regime'}<select value={regime} onChange={e=>setRegime(e.target.value)} style={inputStyle}><option value="CIT">CIT</option><option value="ZAKAT">ZAKAT</option></select></label>
        <label>{ar?'الاتجاه':'Direction'}<select value={direction} onChange={e=>setDirection(e.target.value)} style={inputStyle}><option value="ADD">ADD</option><option value="DEDUCT">DEDUCT</option></select></label>
        <label>{ar?'الكود':'Code'}<input value={code} onChange={e=>setCode(e.target.value)}/></label>
        <label>{ar?'الوصف العربي':'Arabic description'}<input value={descriptionAr} onChange={e=>setDescriptionAr(e.target.value)}/></label>
        <label>{ar?'الوصف الإنجليزي':'English description'}<input value={descriptionEn} onChange={e=>setDescriptionEn(e.target.value)}/></label>
        <label>{ar?'المبلغ':'Amount'}<input type="number" value={adjustmentAmount} onChange={e=>setAdjustmentAmount(e.target.value)}/></label>
        <label>{ar?'حساب المصدر':'Source account'}<input value={sourceAccount} onChange={e=>setSourceAccount(e.target.value)}/></label>
        <label>{ar?'مرجع الإثبات':'Evidence reference'}<input value={evidence} onChange={e=>setEvidence(e.target.value)}/></label>
      </div><div className="journal-footer"><span>{message}</span><button disabled={busy||!selectedReturnId} onClick={addAdjustment}>{ar?'إضافة وإعادة الاحتساب':'Add & recalculate'}</button></div>
      {selected&&<DataTable headers={[ar?'النظام':'Regime',ar?'الاتجاه':'Direction',ar?'الكود':'Code',ar?'الوصف':'Description',ar?'المبلغ':'Amount',ar?'الإثبات':'Evidence']} rows={selected.adjustments.map(x=>[x.regime,x.direction,x.code,ar?x.description_ar:x.description_en,money.format(Number(x.amount)),x.evidence_reference||'—'])}/>} 
    </Panel>

    <Panel title={ar?'سجل الإقرارات السنوية':'Annual return register'} icon={<FileCheck2 size={18}/> }>
      <div className="journal-footer"><span>{ar?'الإقرار داخلي للإعداد والمراجعة؛ الربط الرسمي مع الهيئة خارج RC24.':'Internal preparation return; official ZATCA filing remains external.'}</span><button onClick={()=>download(`/api/v1/zakat-income-tax/export/returns.csv?company_id=${companyId}`,'zakat_income_tax_returns.csv').catch(e=>setMessage(e.message))}><Download size={15}/>{ar?'تصدير الإقرارات':'Export returns'}</button><button onClick={()=>download(`/api/v1/zakat-income-tax/export/adjustments.csv?company_id=${companyId}`,'zakat_income_tax_adjustments.csv').catch(e=>setMessage(e.message))}><Download size={15}/>{ar?'تصدير التعديلات':'Export adjustments'}</button></div>
      <DataTable headers={[ar?'الرقم':'Number',ar?'السنة':'Year',ar?'الاستحقاق':'Due',ar?'الربح المحاسبي':'Accounting PBT',ar?'وعاء ضريبة الدخل':'CIT base',ar?'ضريبة الدخل':'CIT',ar?'وعاء الزكاة':'Zakat base',ar?'الزكاة':'Zakat',ar?'الإجمالي':'Total',ar?'فرق الأستاذ':'GL diff',ar?'الحالة/الإجراء':'Status/action']} rows={returns.map(x=>[x.number,x.period_end.slice(0,4),x.due_date,money.format(Number(x.accounting_profit_before_zakat_tax)),money.format(Number(x.income_tax_base)),money.format(Number(x.income_tax_payable)),money.format(Number(x.zakat_base)),money.format(Number(x.zakat_payable)),money.format(Number(x.total_payable)),money.format(Number(x.reconciliation_difference)),<span key={x.id}>{x.status}{x.status==='DRAFT'&&<button disabled={busy} style={{marginInlineStart:6}} onClick={()=>action(x.id,'submit')}>{ar?'إرسال':'Submit'}</button>}{x.status==='SUBMITTED'&&<button disabled={busy} style={{marginInlineStart:6}} onClick={()=>action(x.id,'approve-post')}>{ar?'اعتماد وترحيل':'Approve & post'}</button>}</span>])}/>
    </Panel>

    <Panel title={ar?'سداد الإقرار المعتمد':'Pay approved return'} icon={<Landmark size={18}/> }>
      <div className="journal-form" style={{gridTemplateColumns:'repeat(4,minmax(0,1fr))'}}><label>{ar?'البنك':'Bank'}<select value={bankId} onChange={e=>setBankId(e.target.value)} style={inputStyle}>{banks.map(x=><option key={x.id} value={x.id}>{x.code} — {ar?x.bank_name_ar:x.bank_name_en}</option>)}</select></label><label>{ar?'تاريخ السداد':'Payment date'}<input type="date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)}/></label><label>{ar?'فاتورة سداد':'SADAD invoice'}<input value={sadad} onChange={e=>setSadad(e.target.value)}/></label><label>{ar?'مرجع الدفع':'Payment reference'}<input value={paymentReference} onChange={e=>setPaymentReference(e.target.value)}/></label></div><div className="journal-footer"><span>{approvedUnpaid?`${approvedUnpaid.number}: ${money.format(Number(approvedUnpaid.total_payable))}`:(ar?'لا يوجد إقرار معتمد غير مسدد.':'No approved unpaid return.')}</span><button disabled={busy||!approvedUnpaid} onClick={pay}>{ar?'سداد وترحيل':'Pay & post'}</button></div>
    </Panel>

    <Panel title={ar?'سجل الخسائر الضريبية':'Tax loss register'} icon={<Landmark size={18}/> }><DataTable headers={[ar?'السنة':'Year',ar?'الأصل':'Original',ar?'المستخدم':'Utilized',ar?'المتاح':'Available',ar?'الحالة':'Status',ar?'الإثبات':'Evidence']} rows={losses.map(x=>[x.origin_year,money.format(Number(x.original_amount)),money.format(Number(x.utilized_amount)),money.format(Number(x.available_amount)),x.status,x.evidence_reference||'—'])}/></Panel>
  </>;
}
