import {Window} from 'happy-dom';
import React, {act} from 'react';
import {createRoot, type Root} from 'react-dom/client';

const baseUrl=process.env.CORVAX_UAT_BASE_URL||'http://127.0.0.1:8142';
const browser=new Window({url:`${baseUrl}/#/quality`});
Object.assign(globalThis,{window:browser,document:browser.document,localStorage:browser.localStorage,sessionStorage:browser.sessionStorage,HTMLElement:browser.HTMLElement,HTMLInputElement:browser.HTMLInputElement,HTMLSelectElement:browser.HTMLSelectElement,Event:browser.Event,CustomEvent:browser.CustomEvent});
Object.defineProperty(globalThis,'navigator',{value:browser.navigator,configurable:true});
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;

type Audit={role:string;method:string;path:string;status:number;detail?:string};
const nativeFetch=globalThis.fetch;const audit:Audit[]=[];let role='setup';
globalThis.fetch=(async(input:RequestInfo|URL,init?:RequestInit)=>{const raw=typeof input==='string'?input:input instanceof URL?input.toString():input.url;const url=raw.startsWith('/')?`${baseUrl}${raw}`:raw;const response=await nativeFetch(url,init);audit.push({role,method:String(init?.method||'GET').toUpperCase(),path:new URL(url).pathname,status:response.status,detail:response.ok?undefined:await response.clone().text()});return response}) as typeof fetch;

const delay=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
function assert(value:unknown,message:string):asserts value{if(!value)throw new Error(message)}
async function json(url:string,init?:RequestInit){const response=await fetch(url,init);const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`${response.status}: ${JSON.stringify(payload)}`);return payload}
async function login(email:string,password:string){return json('/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})})}
async function waitFor(selector:string,predicate:(element:Element)=>boolean=()=>true,timeout=7000){const start=Date.now();while(Date.now()-start<timeout){const element=document.querySelector(selector);if(element&&predicate(element))return element;await act(async()=>{await delay(50)})}throw new Error(`Timeout ${selector}: ${document.body.textContent?.slice(-1800)}`)}
async function setElement(element:HTMLInputElement|HTMLSelectElement,value:string){await act(async()=>{const proto=element instanceof browser.HTMLSelectElement?browser.HTMLSelectElement.prototype:browser.HTMLInputElement.prototype;const setter=Object.getOwnPropertyDescriptor(proto,'value')?.set;assert(setter,'Missing native value setter');setter.call(element,value);element.dispatchEvent(new browser.Event('input',{bubbles:true}));element.dispatchEvent(new browser.Event('change',{bubbles:true}));const propsKey=Object.keys(element).find(key=>key.startsWith('__reactProps$'));const onChange=propsKey?(element as any)[propsKey]?.onChange:null;if(typeof onChange==='function')onChange({target:element,currentTarget:element});await delay(30)})}
async function setField(testId:string,value:string){await setElement(await waitFor(`[data-testid="${testId}"]`) as HTMLInputElement|HTMLSelectElement,value)}
async function setLabel(labelText:string,value:string){const labels=[...document.querySelectorAll('label')];const label=labels.find(row=>(row.textContent||'').trim().startsWith(labelText));assert(label,`Label not found: ${labelText}; page=${document.body.textContent?.slice(-1200)}`);const control=label.querySelector('input,select') as HTMLInputElement|HTMLSelectElement|null;assert(control,`Control not found for ${labelText}`);await setElement(control,value)}
async function click(testId:string){const element=await waitFor(`[data-testid="${testId}"]`) as HTMLButtonElement;assert(!element.disabled,`${testId} disabled`);await act(async()=>{element.dispatchEvent(new browser.MouseEvent('click',{bubbles:true,cancelable:true}));await delay(450)})}

const admin=await login('admin@corvaxplatform.com','Corvax@123');
async function employee(email:string,password:string,roleCode:string,name:string){const created=await json('/api/v1/admin/users',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${admin.access_token}`},body:JSON.stringify({name_ar:name,name_en:name,email,password,require_password_change:false,memberships:[{company_id:1,role_code:roleCode}]})});const session=await login(email,password);return {...session,created};}
const inspector=await employee('r7.quality.inspector@corvaxplatform.com','R7QualityInspector@123','QUALITY_MANAGER','R7 quality inspector');
const qualityVerifier=await employee('r7.quality.verifier@corvaxplatform.com','R7QualityVerifier@123','QUALITY_MANAGER','R7 quality verifier');
const salesManager=await employee('r7.crm.manager@corvaxplatform.com','R7CrmManager@123','SALES_MANAGER','R7 CRM manager');
const requester=await employee('r7.itsm.requester@corvaxplatform.com','R7ItsmRequester@123','ACCOUNTANT','R7 IT service requester');
const itManager=await employee('r7.itsm.manager@corvaxplatform.com','R7ItsmManager@123','IT_MANAGER','R7 IT service manager');
const technician=await employee('r7.itsm.technician@corvaxplatform.com','R7ItsmTechnician@123','IT_MANAGER','R7 IT technician');
const components=await import('../src/dashboard/operationsRealPages');
const container=document.createElement('div');document.body.appendChild(container);let root:Root|null=null;
async function render(component:'quality'|'crm'|'itsm',session:any,roleName:string){role=roleName;sessionStorage.setItem('corvax_token',session.access_token);localStorage.setItem('corvax_user',JSON.stringify(session.user));if(root)await act(async()=>root?.unmount());container.replaceChildren();root=createRoot(container);const Component=component==='quality'?components.QualityPage:component==='crm'?components.CrmEmployeePage:components.ItEmployeePage;await act(async()=>{root?.render(<Component ar={false} companyId={1}/>);await delay(650)});}

// Quality: create a deliberate validation error, record a rejected inspection,
// then remediate and close the NCR under a second employee identity.
await render('quality',inspector,'quality-inspector');await waitFor('[data-testid="quality-create-inspection"]');
await setField('quality-type','INCOMING');await setField('quality-reference-type','PURCHASE_RECEIPT');await setField('quality-reference-id','1');await setField('quality-lot','R7-QA-LOT-001');await setField('quality-inspected','100');await setField('quality-accepted','95');await setField('quality-rejected','10');await setField('quality-severity','HIGH');await click('quality-create-inspection');
assert(audit.some(row=>row.role==='quality-inspector'&&row.path==='/api/v1/quality/inspections'&&row.status===422),'Invalid 105/100 quantity inspection was not rejected');
await setField('quality-accepted','90');await click('quality-create-inspection');
let ncrs=await json('/api/v1/quality/ncrs?company_id=1',{headers:{Authorization:`Bearer ${inspector.access_token}`}});const ncr=ncrs.find((row:any)=>row.description.includes('Rejected 10.0000 of 100.0000'));assert(ncr?.status==='OPEN',`NCR not created: ${JSON.stringify(ncrs)}`);
const qualitySearchBefore=audit.length;await setField('quality-search',ncr.number);assert(audit.length===qualitySearchBefore,'Quality local search called the server');
await render('quality',qualityVerifier,'quality-verifier');await waitFor(`[data-testid="quality-ncr-select"] option[value="${ncr.id}"]`);await setField('quality-ncr-select',String(ncr.id));await setField('quality-root-cause','Inbound seal temperature outside the validated range');await setField('quality-corrective-action','Calibrate sealing station and inspect the next three lots');await setField('quality-ncr-status','IN_PROGRESS');await click('quality-update-ncr');
assert(audit.some(row=>row.role==='quality-verifier'&&row.method==='PATCH'&&row.path.endsWith(`/ncrs/${ncr.id}`)&&row.status===200),`NCR IN_PROGRESS update was not submitted: ${document.body.textContent?.slice(-1000)}`);
await setField('quality-ncr-status','VERIFIED');await click('quality-update-ncr');assert(audit.filter(row=>row.role==='quality-verifier'&&row.method==='PATCH'&&row.path.endsWith(`/ncrs/${ncr.id}`)&&row.status===200).length===2,'NCR VERIFIED update was not submitted');await setField('quality-ncr-status','CLOSED');await click('quality-update-ncr');assert(audit.filter(row=>row.role==='quality-verifier'&&row.method==='PATCH'&&row.path.endsWith(`/ncrs/${ncr.id}`)&&row.status===200).length===3,'NCR CLOSED update was not submitted');
ncrs=await json('/api/v1/quality/ncrs?company_id=1',{headers:{Authorization:`Bearer ${qualityVerifier.access_token}`}});const closedNcr=ncrs.find((row:any)=>row.id===ncr.id);assert(closedNcr?.status==='CLOSED'&&closedNcr.root_cause&&closedNcr.corrective_action,`NCR remediation did not persist: ${JSON.stringify(closedNcr)}`);

// CRM: campaign -> lead -> opportunity -> invalid loss -> negotiation -> won.
await render('crm',salesManager,'crm-manager');await waitFor('[data-testid="crm-create-campaign"]');await setField('crm-campaign-code','R7-CAMPAIGN-01');await setLabel('Arabic name','حملة محاكاة الموظف');await setLabel('English name','R7 employee simulation campaign');await setLabel('Budget','25000');await click('crm-create-campaign');
let campaigns=await json('/api/v1/crm/campaigns?company_id=1',{headers:{Authorization:`Bearer ${salesManager.access_token}`}});const campaign=campaigns.find((row:any)=>row.code==='R7-CAMPAIGN-01');assert(campaign&&Number(campaign.budget)===25000,'Campaign did not persist');
await click('crm-tab-leads');await setLabel('Campaign',String(campaign.id));await setField('crm-lead-name','R7 Industrial Customer');await setLabel('Email','buyer.r7@example.com');await setLabel('Phone','+966500000777');await setLabel('Estimated value','180000');await setLabel('Notes','Qualified from the August industrial event');await click('crm-create-lead');
let leads=await json('/api/v1/crm/leads?company_id=1',{headers:{Authorization:`Bearer ${salesManager.access_token}`}});const lead=leads.find((row:any)=>row.name==='R7 Industrial Customer');assert(lead?.status==='NEW'&&Number(lead.estimated_value)===180000,'Lead did not persist');
await setField('crm-convert-lead',String(lead.id));await setField('crm-opportunity-title','R7 annual supply agreement');await setLabel('Amount','180000');await setLabel('Probability %','40');await click('crm-convert-button');
let opps=await json('/api/v1/crm/opportunities?company_id=1',{headers:{Authorization:`Bearer ${salesManager.access_token}`}});const opp=opps.find((row:any)=>row.lead_id===lead.id);assert(opp?.stage==='QUALIFICATION'&&Number(opp.amount)===180000,'Opportunity conversion failed');
await setField('crm-opportunity-select',String(opp.id));await setField('crm-opportunity-stage','LOST');await click('crm-update-opportunity');assert(audit.some(row=>row.role==='crm-manager'&&row.path.endsWith(`/opportunities/${opp.id}`)&&row.status===422),'Lost opportunity without reason was not rejected');
await setField('crm-opportunity-stage','NEGOTIATION');await setLabel('Probability %','70');await click('crm-update-opportunity');await setField('crm-opportunity-stage','WON');await setLabel('Probability %','100');await click('crm-update-opportunity');
opps=await json('/api/v1/crm/opportunities?company_id=1',{headers:{Authorization:`Bearer ${salesManager.access_token}`}});const won=opps.find((row:any)=>row.id===opp.id);assert(won?.stage==='WON'&&Number(won.probability)===100,'Opportunity was not closed as won');const crmSearchBefore=audit.length;await setField('crm-search',won.number);assert(audit.length===crmSearchBefore,'CRM local search called the server');

// ITSM: manager registers an asset, employee opens a ticket and is denied an
// unauthorized resolution, manager assigns, and a separate technician resolves.
await render('itsm',itManager,'it-manager');await click('itsm-tab-assets');await setField('itsm-asset-tag','R7-LAPTOP-001');await setField('itsm-asset-name','R7 finance operations laptop');await setLabel('Serial number','SN-R7-0001');await setLabel('Criticality','HIGH');await click('itsm-create-asset');
let assets=await json('/api/v1/itsm/assets?company_id=1',{headers:{Authorization:`Bearer ${itManager.access_token}`}});const asset=assets.find((row:any)=>row.asset_tag==='R7-LAPTOP-001');assert(asset?.status==='IN_SERVICE'&&asset.serial_number==='SN-R7-0001','IT asset did not persist');
await render('itsm',requester,'service-requester');await setField('itsm-ticket-subject','ERP approval screen access failure');await setLabel('Category','ACCESS');await setLabel('Priority','HIGH');await setLabel('Due hours','8');await setLabel('Description','User receives permission denied on the purchase approval screen');await click('itsm-create-ticket');
let tickets=await json('/api/v1/itsm/tickets?company_id=1',{headers:{Authorization:`Bearer ${requester.access_token}`}});const ticket=tickets.find((row:any)=>row.subject==='ERP approval screen access failure');assert(ticket?.status==='OPEN','Service ticket did not persist');await setField('itsm-ticket-select',String(ticket.id));await setField('itsm-resolution','Unauthorized test resolution');await click('itsm-resolve-ticket');assert(audit.some(row=>row.role==='service-requester'&&row.path.endsWith(`/tickets/${ticket.id}/resolve`)&&row.status===403),'Requester resolution was not permission denied');
await render('itsm',itManager,'it-manager');await waitFor(`[data-testid="itsm-ticket-select"] option[value="${ticket.id}"]`);await setField('itsm-ticket-select',String(ticket.id));await setField('itsm-assignee-id',String(technician.created.id));await click('itsm-assign-ticket');assert(audit.some(row=>row.role==='it-manager'&&row.path.endsWith(`/tickets/${ticket.id}/assign`)&&row.status===200),'IT manager assignment was not submitted');
await render('itsm',technician,'it-technician');await waitFor(`[data-testid="itsm-ticket-select"] option[value="${ticket.id}"]`);await setField('itsm-ticket-select',String(ticket.id));await click('itsm-start-ticket');assert(audit.some(row=>row.role==='it-technician'&&row.path.endsWith(`/tickets/${ticket.id}/start`)&&row.status===200),'Technician start was not submitted');await setField('itsm-resolution','Role cache refreshed and the approved purchasing role restored');await click('itsm-resolve-ticket');assert(audit.some(row=>row.role==='it-technician'&&row.path.endsWith(`/tickets/${ticket.id}/resolve`)&&row.status===200),'Technician resolution was not submitted');
tickets=await json('/api/v1/itsm/tickets?company_id=1',{headers:{Authorization:`Bearer ${technician.access_token}`}});const resolved=tickets.find((row:any)=>row.id===ticket.id);assert(resolved?.status==='RESOLVED'&&resolved.assignee_user_id===technician.created.id&&resolved.resolution.includes('Role cache'),'Ticket assignment and resolution did not persist');const itsmSearchBefore=audit.length;await setField('itsm-search',resolved.number);assert(audit.length===itsmSearchBefore,'ITSM local search called the server');

const unexpected=audit.filter(row=>row.status>=400&&!((row.path==='/api/v1/quality/inspections'&&row.status===422)||(row.path.endsWith(`/opportunities/${opp.id}`)&&row.status===422)||(row.path.endsWith(`/tickets/${ticket.id}/resolve`)&&row.status===403)));
assert(!unexpected.length,`Unexpected HTTP errors: ${JSON.stringify(unexpected)}`);assert(!audit.some(row=>row.status>=500),`Server errors: ${JSON.stringify(audit.filter(row=>row.status>=500))}`);
console.log(JSON.stringify({database:'fresh isolated SQLite database supplied by runner',quality:{inspection_result:'PARTIAL',intentional_invalid_quantity_status:422,ncr_number:ncr.number,ncr_states:['OPEN','IN_PROGRESS','VERIFIED','CLOSED'],inspector_user_id:inspector.created.id,verifier_user_id:qualityVerifier.created.id,local_search_server_requests:0},crm:{campaign_code:campaign.code,campaign_budget:Number(campaign.budget),lead_number:lead.number,opportunity_number:won.number,opportunity_states:['QUALIFICATION','422 LOST without reason','NEGOTIATION','WON'],won_amount:Number(won.amount),local_search_server_requests:0},itsm:{asset_tag:asset.asset_tag,ticket_number:resolved.number,ticket_states:['OPEN','403 requester resolution','ASSIGNED','IN_PROGRESS','RESOLVED'],requester_user_id:requester.created.id,manager_user_id:itManager.created.id,technician_user_id:technician.created.id,local_search_server_requests:0},requests:audit.length,writes:audit.filter(row=>row.method!=='GET').length,expected_errors:3,unexpected_errors:0,server_errors:0},null,2));
if(root)await act(async()=>root?.unmount());container.remove();
