"""add ar ap treasury subledgers

Revision ID: 1d69512ededa
Revises: ad0734700817
Create Date: 2026-07-11 21:42:57.377332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d69512ededa'
down_revision: Union[str, Sequence[str], None] = 'ad0734700817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_ar', sa.String(length=250), nullable=False),
    sa.Column('name_en', sa.String(length=250), nullable=False),
    sa.Column('party_type', sa.String(length=20), nullable=False),
    sa.Column('vat_number', sa.String(length=30), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_party_company_code')
    )
    op.create_index(op.f('ix_parties_company_id'), 'parties', ['company_id'], unique=False)
    op.create_index(op.f('ix_parties_party_type'), 'parties', ['party_type'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('bank_name_ar', sa.String(length=200), nullable=False),
    sa.Column('bank_name_en', sa.String(length=200), nullable=False),
    sa.Column('iban', sa.String(length=50), nullable=True),
    sa.Column('gl_account_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gl_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_bank_company_code')
    )
    op.create_index(op.f('ix_bank_accounts_company_id'), 'bank_accounts', ['company_id'], unique=False)
    op.create_table('purchase_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_invoice_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_purchase_invoice_company_number')
    )
    op.create_index(op.f('ix_purchase_invoices_company_id'), 'purchase_invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_invoice_date'), 'purchase_invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_number'), 'purchase_invoices', ['number'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_status'), 'purchase_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_supplier_id'), 'purchase_invoices', ['supplier_id'], unique=False)
    op.create_table('sales_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_sales_invoice_company_number')
    )
    op.create_index(op.f('ix_sales_invoices_company_id'), 'sales_invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_invoices_customer_id'), 'sales_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_invoices_invoice_date'), 'sales_invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_sales_invoices_number'), 'sales_invoices', ['number'], unique=False)
    op.create_index(op.f('ix_sales_invoices_status'), 'sales_invoices', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_payment_company_number')
    )
    op.create_index(op.f('ix_payments_company_id'), 'payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payments_number'), 'payments', ['number'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_supplier_id'), 'payments', ['supplier_id'], unique=False)
    op.create_table('purchase_invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('expense_account_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['expense_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['purchase_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_invoice_lines_invoice_id'), 'purchase_invoice_lines', ['invoice_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_receipt_company_number')
    )
    op.create_index(op.f('ix_receipts_company_id'), 'receipts', ['company_id'], unique=False)
    op.create_index(op.f('ix_receipts_customer_id'), 'receipts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_receipts_number'), 'receipts', ['number'], unique=False)
    op.create_index(op.f('ix_receipts_receipt_date'), 'receipts', ['receipt_date'], unique=False)
    op.create_table('sales_invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('revenue_account_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revenue_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_invoice_lines_invoice_id'), 'sales_invoice_lines', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_invoice_lines_invoice_id'), table_name='sales_invoice_lines')
    op.drop_table('sales_invoice_lines')
    op.drop_index(op.f('ix_receipts_receipt_date'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_number'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_customer_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_company_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_purchase_invoice_lines_invoice_id'), table_name='purchase_invoice_lines')
    op.drop_table('purchase_invoice_lines')
    op.drop_index(op.f('ix_payments_supplier_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_sales_invoices_status'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_number'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_invoice_date'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_customer_id'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_company_id'), table_name='sales_invoices')
    op.drop_table('sales_invoices')
    op.drop_index(op.f('ix_purchase_invoices_supplier_id'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_status'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_number'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_invoice_date'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_company_id'), table_name='purchase_invoices')
    op.drop_table('purchase_invoices')
    op.drop_index(op.f('ix_bank_accounts_company_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_parties_party_type'), table_name='parties')
    op.drop_index(op.f('ix_parties_company_id'), table_name='parties')
    op.drop_table('parties')
    # ### end Alembic commands ###
