"""operational engines v012

Revision ID: 937e43f4e4a7
Revises: 1d69512ededa
Create Date: 2026-07-11 21:54:25.726288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937e43f4e4a7'
down_revision: Union[str, Sequence[str], None] = '1d69512ededa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('member_number', sa.String(length=40), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'member_number', name='uq_member_company_number')
    )
    op.create_index(op.f('ix_members_company_id'), 'members', ['company_id'], unique=False)
    op.create_table('membership_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('net_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_plan_company_code')
    )
    op.create_index(op.f('ix_membership_plans_company_id'), 'membership_plans', ['company_id'], unique=False)
    op.create_table('work_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('hourly_labor_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('hourly_overhead_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_work_center_company_code')
    )
    op.create_index(op.f('ix_work_centers_company_id'), 'work_centers', ['company_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', 'fiscal_year_id', name='uq_budget_company_name_year')
    )
    op.create_index(op.f('ix_budgets_company_id'), 'budgets', ['company_id'], unique=False)
    op.create_index(op.f('ix_budgets_status'), 'budgets', ['status'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name_ar', sa.String(length=250), nullable=False),
    sa.Column('name_en', sa.String(length=250), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('valuation_method', sa.String(length=30), nullable=False),
    sa.Column('standard_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('inventory_account_id', sa.Integer(), nullable=False),
    sa.Column('cogs_account_id', sa.Integer(), nullable=False),
    sa.Column('revenue_account_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cogs_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['revenue_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_item_company_code')
    )
    op.create_index(op.f('ix_items_code'), 'items', ['code'], unique=False)
    op.create_index(op.f('ix_items_company_id'), 'items', ['company_id'], unique=False)
    op.create_index(op.f('ix_items_item_type'), 'items', ['item_type'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('warehouse_type', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_warehouse_company_code')
    )
    op.create_index(op.f('ix_warehouses_company_id'), 'warehouses', ['company_id'], unique=False)
    op.create_table('bank_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_account_id', 'statement_date', name='uq_bank_statement_date')
    )
    op.create_index(op.f('ix_bank_statements_bank_account_id'), 'bank_statements', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_statements_company_id'), 'bank_statements', ['company_id'], unique=False)
    op.create_index(op.f('ix_bank_statements_statement_date'), 'bank_statements', ['statement_date'], unique=False)
    op.create_index(op.f('ix_bank_statements_status'), 'bank_statements', ['status'], unique=False)
    op.create_table('bills_of_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('finished_item_id', sa.Integer(), nullable=False),
    sa.Column('output_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('work_center_id', sa.Integer(), nullable=True),
    sa.Column('standard_hours', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finished_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', 'version', name='uq_bom_company_code_version')
    )
    op.create_index(op.f('ix_bills_of_material_company_id'), 'bills_of_material', ['company_id'], unique=False)
    op.create_index(op.f('ix_bills_of_material_status'), 'bills_of_material', ['status'], unique=False)
    op.create_table('budget_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('committed_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reserved_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'account_id', 'cost_center_id', 'period_number', name='uq_budget_line_dimension')
    )
    op.create_index(op.f('ix_budget_lines_account_id'), 'budget_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_budget_lines_budget_id'), 'budget_lines', ['budget_id'], unique=False)
    op.create_table('lease_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('name_ar', sa.String(length=250), nullable=False),
    sa.Column('name_en', sa.String(length=250), nullable=False),
    sa.Column('commencement_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_frequency_months', sa.Integer(), nullable=False),
    sa.Column('payment_timing', sa.String(length=20), nullable=False),
    sa.Column('annual_discount_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('initial_liability', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('initial_rou_asset', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('initial_journal_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['initial_journal_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_lease_company_number')
    )
    op.create_index(op.f('ix_lease_contracts_company_id'), 'lease_contracts', ['company_id'], unique=False)
    op.create_index(op.f('ix_lease_contracts_number'), 'lease_contracts', ['number'], unique=False)
    op.create_index(op.f('ix_lease_contracts_status'), 'lease_contracts', ['status'], unique=False)
    op.create_table('membership_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('sale_journal_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ),
    sa.ForeignKeyConstraint(['sale_journal_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_membership_contract_company_number')
    )
    op.create_index(op.f('ix_membership_contracts_company_id'), 'membership_contracts', ['company_id'], unique=False)
    op.create_index(op.f('ix_membership_contracts_number'), 'membership_contracts', ['number'], unique=False)
    op.create_index(op.f('ix_membership_contracts_status'), 'membership_contracts', ['status'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_po_company_number')
    )
    op.create_index(op.f('ix_purchase_orders_company_id'), 'purchase_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_number'), 'purchase_orders', ['number'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_table('quality_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('inspection_type', sa.String(length=30), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('lot_number', sa.String(length=80), nullable=True),
    sa.Column('inspected_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('accepted_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_quality_inspection_company_number')
    )
    op.create_index(op.f('ix_quality_inspections_company_id'), 'quality_inspections', ['company_id'], unique=False)
    op.create_index(op.f('ix_quality_inspections_number'), 'quality_inspections', ['number'], unique=False)
    op.create_index(op.f('ix_quality_inspections_result'), 'quality_inspections', ['result'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('lot_number', sa.String(length=80), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_company_id'), 'stock_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_item_id'), 'stock_movements', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_movement_date'), 'stock_movements', ['movement_date'], unique=False)
    op.create_index(op.f('ix_stock_movements_movement_type'), 'stock_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_stock_movements_warehouse_id'), 'stock_movements', ['warehouse_id'], unique=False)
    op.create_table('bank_statement_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('matched_journal_line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['matched_journal_line_id'], ['journal_lines.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['bank_statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_statement_lines_statement_id'), 'bank_statement_lines', ['statement_id'], unique=False)
    op.create_index(op.f('ix_bank_statement_lines_status'), 'bank_statement_lines', ['status'], unique=False)
    op.create_index(op.f('ix_bank_statement_lines_transaction_date'), 'bank_statement_lines', ['transaction_date'], unique=False)
    op.create_table('bill_of_material_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('component_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('scrap_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['bills_of_material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_of_material_lines_bom_id'), 'bill_of_material_lines', ['bom_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_grn_company_number')
    )
    op.create_index(op.f('ix_goods_receipts_company_id'), 'goods_receipts', ['company_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_number'), 'goods_receipts', ['number'], unique=False)
    op.create_index(op.f('ix_goods_receipts_purchase_order_id'), 'goods_receipts', ['purchase_order_id'], unique=False)
    op.create_table('lease_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('opening_liability', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_liability', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('depreciation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['lease_id'], ['lease_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lease_id', 'period_number', name='uq_lease_schedule_period')
    )
    op.create_index(op.f('ix_lease_schedules_lease_id'), 'lease_schedules', ['lease_id'], unique=False)
    op.create_index(op.f('ix_lease_schedules_payment_date'), 'lease_schedules', ['payment_date'], unique=False)
    op.create_index(op.f('ix_lease_schedules_status'), 'lease_schedules', ['status'], unique=False)
    op.create_table('non_conformances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['quality_inspections.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_ncr_company_number')
    )
    op.create_index(op.f('ix_non_conformances_company_id'), 'non_conformances', ['company_id'], unique=False)
    op.create_index(op.f('ix_non_conformances_number'), 'non_conformances', ['number'], unique=False)
    op.create_index(op.f('ix_non_conformances_status'), 'non_conformances', ['status'], unique=False)
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('planned_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('completed_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('planned_hours', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('material_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('overhead_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('issue_journal_id', sa.Integer(), nullable=True),
    sa.Column('completion_journal_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['bills_of_material.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completion_journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_production_order_company_number')
    )
    op.create_index(op.f('ix_production_orders_company_id'), 'production_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_production_orders_number'), 'production_orders', ['number'], unique=False)
    op.create_index(op.f('ix_production_orders_status'), 'production_orders', ['status'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('invoiced_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_purchase_order_id'), 'purchase_order_lines', ['purchase_order_id'], unique=False)
    op.create_table('revenue_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('recognition_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('recognized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['membership_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'period_number', name='uq_contract_revenue_period')
    )
    op.create_index(op.f('ix_revenue_schedules_contract_id'), 'revenue_schedules', ['contract_id'], unique=False)
    op.create_index(op.f('ix_revenue_schedules_recognition_date'), 'revenue_schedules', ['recognition_date'], unique=False)
    op.create_index(op.f('ix_revenue_schedules_status'), 'revenue_schedules', ['status'], unique=False)
    op.create_table('goods_receipt_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goods_receipt_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('lot_number', sa.String(length=80), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipt_lines_goods_receipt_id'), 'goods_receipt_lines', ['goods_receipt_id'], unique=False)
    op.create_table('production_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('planned_minutes', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('downtime_minutes', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ideal_cycle_seconds', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_units', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('good_units', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('availability', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('performance', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('quality', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('oee', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_runs_company_id'), 'production_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_production_runs_production_order_id'), 'production_runs', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_production_runs_run_date'), 'production_runs', ['run_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_runs_run_date'), table_name='production_runs')
    op.drop_index(op.f('ix_production_runs_production_order_id'), table_name='production_runs')
    op.drop_index(op.f('ix_production_runs_company_id'), table_name='production_runs')
    op.drop_table('production_runs')
    op.drop_index(op.f('ix_goods_receipt_lines_goods_receipt_id'), table_name='goods_receipt_lines')
    op.drop_table('goods_receipt_lines')
    op.drop_index(op.f('ix_revenue_schedules_status'), table_name='revenue_schedules')
    op.drop_index(op.f('ix_revenue_schedules_recognition_date'), table_name='revenue_schedules')
    op.drop_index(op.f('ix_revenue_schedules_contract_id'), table_name='revenue_schedules')
    op.drop_table('revenue_schedules')
    op.drop_index(op.f('ix_purchase_order_lines_purchase_order_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_production_orders_status'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_number'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_company_id'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_non_conformances_status'), table_name='non_conformances')
    op.drop_index(op.f('ix_non_conformances_number'), table_name='non_conformances')
    op.drop_index(op.f('ix_non_conformances_company_id'), table_name='non_conformances')
    op.drop_table('non_conformances')
    op.drop_index(op.f('ix_lease_schedules_status'), table_name='lease_schedules')
    op.drop_index(op.f('ix_lease_schedules_payment_date'), table_name='lease_schedules')
    op.drop_index(op.f('ix_lease_schedules_lease_id'), table_name='lease_schedules')
    op.drop_table('lease_schedules')
    op.drop_index(op.f('ix_goods_receipts_purchase_order_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_number'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_company_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_bill_of_material_lines_bom_id'), table_name='bill_of_material_lines')
    op.drop_table('bill_of_material_lines')
    op.drop_index(op.f('ix_bank_statement_lines_transaction_date'), table_name='bank_statement_lines')
    op.drop_index(op.f('ix_bank_statement_lines_status'), table_name='bank_statement_lines')
    op.drop_index(op.f('ix_bank_statement_lines_statement_id'), table_name='bank_statement_lines')
    op.drop_table('bank_statement_lines')
    op.drop_index(op.f('ix_stock_movements_warehouse_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_type'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_date'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_item_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_company_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_quality_inspections_result'), table_name='quality_inspections')
    op.drop_index(op.f('ix_quality_inspections_number'), table_name='quality_inspections')
    op.drop_index(op.f('ix_quality_inspections_company_id'), table_name='quality_inspections')
    op.drop_table('quality_inspections')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_company_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_membership_contracts_status'), table_name='membership_contracts')
    op.drop_index(op.f('ix_membership_contracts_number'), table_name='membership_contracts')
    op.drop_index(op.f('ix_membership_contracts_company_id'), table_name='membership_contracts')
    op.drop_table('membership_contracts')
    op.drop_index(op.f('ix_lease_contracts_status'), table_name='lease_contracts')
    op.drop_index(op.f('ix_lease_contracts_number'), table_name='lease_contracts')
    op.drop_index(op.f('ix_lease_contracts_company_id'), table_name='lease_contracts')
    op.drop_table('lease_contracts')
    op.drop_index(op.f('ix_budget_lines_budget_id'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_account_id'), table_name='budget_lines')
    op.drop_table('budget_lines')
    op.drop_index(op.f('ix_bills_of_material_status'), table_name='bills_of_material')
    op.drop_index(op.f('ix_bills_of_material_company_id'), table_name='bills_of_material')
    op.drop_table('bills_of_material')
    op.drop_index(op.f('ix_bank_statements_status'), table_name='bank_statements')
    op.drop_index(op.f('ix_bank_statements_statement_date'), table_name='bank_statements')
    op.drop_index(op.f('ix_bank_statements_company_id'), table_name='bank_statements')
    op.drop_index(op.f('ix_bank_statements_bank_account_id'), table_name='bank_statements')
    op.drop_table('bank_statements')
    op.drop_index(op.f('ix_warehouses_company_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_items_item_type'), table_name='items')
    op.drop_index(op.f('ix_items_company_id'), table_name='items')
    op.drop_index(op.f('ix_items_code'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_budgets_status'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_company_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_work_centers_company_id'), table_name='work_centers')
    op.drop_table('work_centers')
    op.drop_index(op.f('ix_membership_plans_company_id'), table_name='membership_plans')
    op.drop_table('membership_plans')
    op.drop_index(op.f('ix_members_company_id'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
