"""fixed assets payroll restaurant pos v014

Revision ID: 9755f6dddb11
Revises: 937e43f4e4a7
Create Date: 2026-07-11 22:05:36.084491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9755f6dddb11'
down_revision: Union[str, Sequence[str], None] = '937e43f4e4a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_delivery_platform_company_code')
    )
    op.create_index(op.f('ix_delivery_platforms_company_id'), 'delivery_platforms', ['company_id'], unique=False)
    op.create_table('asset_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('asset_account_id', sa.Integer(), nullable=False),
    sa.Column('accumulated_depreciation_account_id', sa.Integer(), nullable=False),
    sa.Column('depreciation_expense_account_id', sa.Integer(), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('residual_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('depreciation_convention', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['accumulated_depreciation_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['asset_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depreciation_expense_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_asset_category_company_code')
    )
    op.create_index(op.f('ix_asset_categories_company_id'), 'asset_categories', ['company_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=40), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('nationality_group', sa.String(length=20), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('housing_allowance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_allowance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('employee_gosi_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('employer_gosi_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employee_number', name='uq_employee_company_number')
    )
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=False)
    op.create_table('fixed_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('asset_number', sa.String(length=40), nullable=False),
    sa.Column('name_ar', sa.String(length=250), nullable=False),
    sa.Column('name_en', sa.String(length=250), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('in_service_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('residual_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('depreciation_method', sa.String(length=30), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_book_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acquisition_journal_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acquisition_journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['asset_categories.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'asset_number', name='uq_fixed_asset_company_number')
    )
    op.create_index(op.f('ix_fixed_assets_asset_number'), 'fixed_assets', ['asset_number'], unique=False)
    op.create_index(op.f('ix_fixed_assets_company_id'), 'fixed_assets', ['company_id'], unique=False)
    op.create_index(op.f('ix_fixed_assets_status'), 'fixed_assets', ['status'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_employee_gosi', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_employer_gosi', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('payment_journal_id', sa.Integer(), nullable=True),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['payment_journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_year', 'period_month', name='uq_payroll_company_period')
    )
    op.create_index(op.f('ix_payroll_runs_company_id'), 'payroll_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_payroll_runs_status'), 'payroll_runs', ['status'], unique=False)
    op.create_table('pos_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('payment_channel', sa.String(length=20), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('food_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sale_journal_id', sa.Integer(), nullable=False),
    sa.Column('cogs_journal_id', sa.Integer(), nullable=False),
    sa.Column('settlement_journal_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['cogs_journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['delivery_platforms.id'], ),
    sa.ForeignKeyConstraint(['sale_journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['settlement_journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_pos_order_company_number')
    )
    op.create_index(op.f('ix_pos_orders_company_id'), 'pos_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_pos_orders_number'), 'pos_orders', ['number'], unique=False)
    op.create_index(op.f('ix_pos_orders_order_date'), 'pos_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_pos_orders_status'), 'pos_orders', ['status'], unique=False)
    op.create_table('asset_depreciation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('opening_nbv', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('depreciation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_nbv', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['fixed_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'period_date', name='uq_asset_depreciation_period')
    )
    op.create_index(op.f('ix_asset_depreciation_asset_id'), 'asset_depreciation', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_depreciation_period_date'), 'asset_depreciation', ['period_date'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('recipe_bom_id', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['recipe_bom_id'], ['bills_of_material.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_menu_item_company_code')
    )
    op.create_index(op.f('ix_menu_items_company_id'), 'menu_items', ['company_id'], unique=False)
    op.create_table('payroll_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('housing_allowance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_allowance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('employee_gosi', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('employer_gosi', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', name='uq_payroll_line_employee')
    )
    op.create_index(op.f('ix_payroll_lines_payroll_run_id'), 'payroll_lines', ['payroll_run_id'], unique=False)
    op.create_table('pos_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos_order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('food_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['pos_order_id'], ['pos_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_order_lines_pos_order_id'), 'pos_order_lines', ['pos_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pos_order_lines_pos_order_id'), table_name='pos_order_lines')
    op.drop_table('pos_order_lines')
    op.drop_index(op.f('ix_payroll_lines_payroll_run_id'), table_name='payroll_lines')
    op.drop_table('payroll_lines')
    op.drop_index(op.f('ix_menu_items_company_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_asset_depreciation_period_date'), table_name='asset_depreciation')
    op.drop_index(op.f('ix_asset_depreciation_asset_id'), table_name='asset_depreciation')
    op.drop_table('asset_depreciation')
    op.drop_index(op.f('ix_pos_orders_status'), table_name='pos_orders')
    op.drop_index(op.f('ix_pos_orders_order_date'), table_name='pos_orders')
    op.drop_index(op.f('ix_pos_orders_number'), table_name='pos_orders')
    op.drop_index(op.f('ix_pos_orders_company_id'), table_name='pos_orders')
    op.drop_table('pos_orders')
    op.drop_index(op.f('ix_payroll_runs_status'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_company_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_fixed_assets_status'), table_name='fixed_assets')
    op.drop_index(op.f('ix_fixed_assets_company_id'), table_name='fixed_assets')
    op.drop_index(op.f('ix_fixed_assets_asset_number'), table_name='fixed_assets')
    op.drop_table('fixed_assets')
    op.drop_index(op.f('ix_employees_employee_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_asset_categories_company_id'), table_name='asset_categories')
    op.drop_table('asset_categories')
    op.drop_index(op.f('ix_delivery_platforms_company_id'), table_name='delivery_platforms')
    op.drop_table('delivery_platforms')
    # ### end Alembic commands ###
