"""security hr compliance close backups v016

Revision ID: d95c5098650e
Revises: 9755f6dddb11
Create Date: 2026-07-11 22:22:31.141923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95c5098650e'
down_revision: Union[str, Sequence[str], None] = '9755f6dddb11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_rule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=False),
    sa.Column('name_ar', sa.String(length=250), nullable=False),
    sa.Column('name_en', sa.String(length=250), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'effective_from', name='uq_legal_rule_effective')
    )
    op.create_index(op.f('ix_legal_rule_versions_code'), 'legal_rule_versions', ['code'], unique=False)
    op.create_index(op.f('ix_legal_rule_versions_effective_from'), 'legal_rule_versions', ['effective_from'], unique=False)
    op.create_table('backup_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('backup_type', sa.String(length=30), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_records_company_id'), 'backup_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_backup_records_created_at'), 'backup_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_backup_records_status'), 'backup_records', ['status'], unique=False)
    op.create_table('e_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('invoice_counter', sa.Integer(), nullable=False),
    sa.Column('issue_datetime', sa.DateTime(), nullable=False),
    sa.Column('invoice_type_code', sa.String(length=20), nullable=False),
    sa.Column('xml_content', sa.Text(), nullable=False),
    sa.Column('invoice_hash', sa.String(length=128), nullable=False),
    sa.Column('previous_invoice_hash', sa.String(length=128), nullable=False),
    sa.Column('qr_tlv_base64', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('validation_errors', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'uuid', name='uq_einvoice_company_uuid')
    )
    op.create_index(op.f('ix_e_invoices_company_id'), 'e_invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_e_invoices_source_id'), 'e_invoices', ['source_id'], unique=False)
    op.create_index(op.f('ix_e_invoices_source_type'), 'e_invoices', ['source_type'], unique=False)
    op.create_index(op.f('ix_e_invoices_status'), 'e_invoices', ['status'], unique=False)
    op.create_table('leave_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('affects_payroll', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_leave_type_company_code')
    )
    op.create_index(op.f('ix_leave_types_company_id'), 'leave_types', ['company_id'], unique=False)
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_history_created_at'), 'password_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_ar', sa.String(length=150), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_shift_company_code')
    )
    op.create_index(op.f('ix_shifts_company_id'), 'shifts', ['company_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('vat_return_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('standard_rated_sales', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('output_vat', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('standard_rated_purchases', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('input_vat', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_vat_payable', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_start', 'period_end', name='uq_vat_return_period')
    )
    op.create_index(op.f('ix_vat_return_snapshots_company_id'), 'vat_return_snapshots', ['company_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=True),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('early_leave_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('geofence_valid', sa.Boolean(), nullable=True),
    sa.Column('manual_reason', sa.String(length=500), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_attendance_employee_date')
    )
    op.create_index(op.f('ix_attendance_records_company_id'), 'attendance_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_status'), 'attendance_records', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_records_work_date'), 'attendance_records', ['work_date'], unique=False)
    op.create_table('employee_shift_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_shift_assignments_company_id'), 'employee_shift_assignments', ['company_id'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_employee_id'), 'employee_shift_assignments', ['employee_id'], unique=False)
    op.create_table('end_of_service_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=False),
    sa.Column('termination_reason', sa.String(length=40), nullable=False),
    sa.Column('service_days', sa.Integer(), nullable=False),
    sa.Column('last_wage', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_award', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('entitlement_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('award_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('leave_encashment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_settlement', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['legal_rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_eos_company_number')
    )
    op.create_index(op.f('ix_end_of_service_settlements_company_id'), 'end_of_service_settlements', ['company_id'], unique=False)
    op.create_index(op.f('ix_end_of_service_settlements_employee_id'), 'end_of_service_settlements', ['employee_id'], unique=False)
    op.create_index(op.f('ix_end_of_service_settlements_number'), 'end_of_service_settlements', ['number'], unique=False)
    op.create_index(op.f('ix_end_of_service_settlements_status'), 'end_of_service_settlements', ['status'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uq_leave_company_number')
    )
    op.create_index(op.f('ix_leave_requests_company_id'), 'leave_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_number'), 'leave_requests', ['number'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.create_table('period_close_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_period_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['fiscal_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_period_id', name='uq_close_company_period')
    )
    op.create_index(op.f('ix_period_close_runs_company_id'), 'period_close_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_period_close_runs_status'), 'period_close_runs', ['status'], unique=False)
    op.create_table('period_close_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('close_run_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name_ar', sa.String(length=250), nullable=False),
    sa.Column('name_en', sa.String(length=250), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['close_run_id'], ['period_close_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('close_run_id', 'code', name='uq_close_check_code')
    )
    op.create_index(op.f('ix_period_close_checks_close_run_id'), 'period_close_checks', ['close_run_id'], unique=False)
    op.add_column('branches', sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('branches', sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('branches', sa.Column('geofence_radius_m', sa.Integer(), nullable=False, server_default='200'))
    op.add_column('employees', sa.Column('job_title_ar', sa.String(length=200), nullable=True))
    op.add_column('employees', sa.Column('job_title_en', sa.String(length=200), nullable=True))
    op.add_column('employees', sa.Column('contract_type', sa.String(length=30), nullable=False, server_default='UNLIMITED'))
    op.add_column('employees', sa.Column('contract_end_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('probation_end_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('work_email', sa.String(length=320), nullable=True))
    op.add_column('employees', sa.Column('mobile', sa.String(length=30), nullable=True))
    op.add_column('employees', sa.Column('iban', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('annual_leave_days', sa.Numeric(precision=8, scale=2), nullable=False, server_default='30'))
    op.add_column('employees', sa.Column('employment_status', sa.String(length=20), nullable=False, server_default='ACTIVE'))
    op.add_column('employees', sa.Column('termination_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('users', sa.Column('require_password_change', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'require_password_change')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('employees', 'termination_date')
    op.drop_column('employees', 'employment_status')
    op.drop_column('employees', 'annual_leave_days')
    op.drop_column('employees', 'iban')
    op.drop_column('employees', 'mobile')
    op.drop_column('employees', 'work_email')
    op.drop_column('employees', 'probation_end_date')
    op.drop_column('employees', 'contract_end_date')
    op.drop_column('employees', 'contract_type')
    op.drop_column('employees', 'job_title_en')
    op.drop_column('employees', 'job_title_ar')
    op.drop_column('branches', 'geofence_radius_m')
    op.drop_column('branches', 'longitude')
    op.drop_column('branches', 'latitude')
    op.drop_index(op.f('ix_period_close_checks_close_run_id'), table_name='period_close_checks')
    op.drop_table('period_close_checks')
    op.drop_index(op.f('ix_period_close_runs_status'), table_name='period_close_runs')
    op.drop_index(op.f('ix_period_close_runs_company_id'), table_name='period_close_runs')
    op.drop_table('period_close_runs')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_number'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_company_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_end_of_service_settlements_status'), table_name='end_of_service_settlements')
    op.drop_index(op.f('ix_end_of_service_settlements_number'), table_name='end_of_service_settlements')
    op.drop_index(op.f('ix_end_of_service_settlements_employee_id'), table_name='end_of_service_settlements')
    op.drop_index(op.f('ix_end_of_service_settlements_company_id'), table_name='end_of_service_settlements')
    op.drop_table('end_of_service_settlements')
    op.drop_index(op.f('ix_employee_shift_assignments_employee_id'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_company_id'), table_name='employee_shift_assignments')
    op.drop_table('employee_shift_assignments')
    op.drop_index(op.f('ix_attendance_records_work_date'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_status'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_company_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_vat_return_snapshots_company_id'), table_name='vat_return_snapshots')
    op.drop_table('vat_return_snapshots')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_shifts_company_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
    op.drop_index(op.f('ix_password_history_created_at'), table_name='password_history')
    op.drop_table('password_history')
    op.drop_index(op.f('ix_leave_types_company_id'), table_name='leave_types')
    op.drop_table('leave_types')
    op.drop_index(op.f('ix_e_invoices_status'), table_name='e_invoices')
    op.drop_index(op.f('ix_e_invoices_source_type'), table_name='e_invoices')
    op.drop_index(op.f('ix_e_invoices_source_id'), table_name='e_invoices')
    op.drop_index(op.f('ix_e_invoices_company_id'), table_name='e_invoices')
    op.drop_table('e_invoices')
    op.drop_index(op.f('ix_backup_records_status'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_created_at'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_company_id'), table_name='backup_records')
    op.drop_table('backup_records')
    op.drop_index(op.f('ix_legal_rule_versions_effective_from'), table_name='legal_rule_versions')
    op.drop_index(op.f('ix_legal_rule_versions_code'), table_name='legal_rule_versions')
    op.drop_table('legal_rule_versions')
    # ### end Alembic commands ###
