"""ifrs9 and maintenance v020
Revision ID: e20000000001
Revises: e18000000001
"""
from alembic import op
import sqlalchemy as sa
revision='e20000000001'; down_revision='e18000000001'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('credit_risk_portfolios', sa.Column('id',sa.Integer(),primary_key=True),sa.Column('company_id',sa.Integer(),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('code',sa.String(40),nullable=False),sa.Column('name_ar',sa.String(200),nullable=False),sa.Column('name_en',sa.String(200),nullable=False),sa.Column('method',sa.String(30),nullable=False,server_default='SIMPLIFIED'),sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_by',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.UniqueConstraint('company_id','code',name='uq_credit_portfolio_company_code'))
    op.create_table('credit_risk_buckets', sa.Column('id',sa.Integer(),primary_key=True),sa.Column('portfolio_id',sa.Integer(),sa.ForeignKey('credit_risk_portfolios.id',ondelete='CASCADE'),nullable=False),sa.Column('min_days',sa.Integer(),nullable=False),sa.Column('max_days',sa.Integer()),sa.Column('loss_rate',sa.Numeric(10,6),nullable=False),sa.Column('forward_factor',sa.Numeric(10,6),nullable=False,server_default='1'),sa.UniqueConstraint('portfolio_id','min_days','max_days',name='uq_credit_bucket_range'))
    op.create_table('credit_exposures', sa.Column('id',sa.Integer(),primary_key=True),sa.Column('company_id',sa.Integer(),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('portfolio_id',sa.Integer(),sa.ForeignKey('credit_risk_portfolios.id',ondelete='CASCADE'),nullable=False),sa.Column('reference',sa.String(80),nullable=False),sa.Column('customer_name',sa.String(250),nullable=False),sa.Column('due_date',sa.Date(),nullable=False),sa.Column('gross_amount',sa.Numeric(18,2),nullable=False),sa.Column('carrying_amount',sa.Numeric(18,2),nullable=False),sa.Column('status',sa.String(25),nullable=False,server_default='OPEN'),sa.Column('created_at',sa.DateTime(),nullable=False))
    op.create_table('ecl_runs', sa.Column('id',sa.Integer(),primary_key=True),sa.Column('company_id',sa.Integer(),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('portfolio_id',sa.Integer(),sa.ForeignKey('credit_risk_portfolios.id',ondelete='CASCADE'),nullable=False),sa.Column('as_of_date',sa.Date(),nullable=False),sa.Column('total_exposure',sa.Numeric(18,2),nullable=False,server_default='0'),sa.Column('expected_credit_loss',sa.Numeric(18,2),nullable=False,server_default='0'),sa.Column('status',sa.String(25),nullable=False,server_default='CALCULATED'),sa.Column('journal_id',sa.Integer(),sa.ForeignKey('journal_entries.id')),sa.Column('created_by',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False))
    op.create_table('ecl_run_lines', sa.Column('id',sa.Integer(),primary_key=True),sa.Column('run_id',sa.Integer(),sa.ForeignKey('ecl_runs.id',ondelete='CASCADE'),nullable=False),sa.Column('exposure_id',sa.Integer(),sa.ForeignKey('credit_exposures.id',ondelete='CASCADE'),nullable=False),sa.Column('days_past_due',sa.Integer(),nullable=False),sa.Column('loss_rate',sa.Numeric(10,6),nullable=False),sa.Column('forward_factor',sa.Numeric(10,6),nullable=False),sa.Column('ecl_amount',sa.Numeric(18,2),nullable=False))
    op.create_table('maintenance_assets', sa.Column('id',sa.Integer(),primary_key=True),sa.Column('company_id',sa.Integer(),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('code',sa.String(50),nullable=False),sa.Column('name_ar',sa.String(200),nullable=False),sa.Column('name_en',sa.String(200),nullable=False),sa.Column('branch_id',sa.Integer(),sa.ForeignKey('branches.id')),sa.Column('production_line',sa.String(120)),sa.Column('meter_hours',sa.Numeric(18,2),nullable=False,server_default='0'),sa.Column('criticality',sa.String(20),nullable=False,server_default='MEDIUM'),sa.Column('status',sa.String(20),nullable=False,server_default='ACTIVE'),sa.Column('created_at',sa.DateTime(),nullable=False),sa.UniqueConstraint('company_id','code',name='uq_maintenance_asset_company_code'))
    op.create_table('maintenance_work_orders', sa.Column('id',sa.Integer(),primary_key=True),sa.Column('company_id',sa.Integer(),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('number',sa.String(50),nullable=False),sa.Column('asset_id',sa.Integer(),sa.ForeignKey('maintenance_assets.id',ondelete='CASCADE'),nullable=False),sa.Column('work_type',sa.String(30),nullable=False),sa.Column('priority',sa.String(20),nullable=False,server_default='MEDIUM'),sa.Column('description',sa.String(500),nullable=False),sa.Column('status',sa.String(25),nullable=False,server_default='OPEN'),sa.Column('requested_at',sa.DateTime(),nullable=False),sa.Column('started_at',sa.DateTime()),sa.Column('completed_at',sa.DateTime()),sa.Column('downtime_minutes',sa.Integer(),nullable=False,server_default='0'),sa.Column('labor_cost',sa.Numeric(18,2),nullable=False,server_default='0'),sa.Column('parts_cost',sa.Numeric(18,2),nullable=False,server_default='0'),sa.Column('created_by',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('approved_by',sa.Integer(),sa.ForeignKey('users.id')),sa.UniqueConstraint('company_id','number',name='uq_maintenance_wo_company_number'))

def downgrade():
    for t in ['maintenance_work_orders','maintenance_assets','ecl_run_lines','ecl_runs','credit_exposures','credit_risk_buckets','credit_risk_portfolios']:
        op.drop_table(t)
